// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conferencebody.proto

package easemob.pb;

public final class Conferencebody {
  private Conferencebody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ConferenceBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:easemob.pb.ConferenceBody)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string session_id = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional string session_id = 1;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string session_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
     */
    boolean hasOperation();
    /**
     * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
     */
    easemob.pb.Conferencebody.ConferenceBody.Operation getOperation();

    /**
     * <code>optional string conference_id = 3;</code>
     */
    boolean hasConferenceId();
    /**
     * <code>optional string conference_id = 3;</code>
     */
    java.lang.String getConferenceId();
    /**
     * <code>optional string conference_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getConferenceIdBytes();

    /**
     * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
     */
    easemob.pb.Conferencebody.ConferenceBody.Type getType();

    /**
     * <code>optional string content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 5;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    boolean hasNetwork();
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    java.lang.String getNetwork();
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    com.google.protobuf.ByteString
        getNetworkBytes();

    /**
     * <code>optional string version = 7;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 7;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 7;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
     */
    boolean hasIdentity();
    /**
     * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
     */
    easemob.pb.Conferencebody.ConferenceBody.Identity getIdentity();

    /**
     * <code>optional string duration = 9;</code>
     */
    boolean hasDuration();
    /**
     * <code>optional string duration = 9;</code>
     */
    java.lang.String getDuration();
    /**
     * <code>optional string duration = 9;</code>
     */
    com.google.protobuf.ByteString
        getDurationBytes();

    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    boolean hasPeerName();
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    java.lang.String getPeerName();
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();

    /**
     * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
     *
     * <pre>
     *terminate
     * </pre>
     */
    boolean hasEndReason();
    /**
     * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
     *
     * <pre>
     *terminate
     * </pre>
     */
    easemob.pb.Conferencebody.ConferenceBody.EndReason getEndReason();

    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    easemob.pb.Conferencebody.ConferenceBody.Status getStatus();

    /**
     * <code>optional bool is_direct = 13;</code>
     *
     * <pre>
     *stream update
     * </pre>
     */
    boolean hasIsDirect();
    /**
     * <code>optional bool is_direct = 13;</code>
     *
     * <pre>
     *stream update
     * </pre>
     */
    boolean getIsDirect();

    /**
     * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
     */
    boolean hasControlType();
    /**
     * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
     */
    easemob.pb.Conferencebody.ConferenceBody.StreamControlType getControlType();
  }
  /**
   * Protobuf type {@code easemob.pb.ConferenceBody}
   */
  public  static final class ConferenceBody extends
      com.google.protobuf.GeneratedMessageLite<
          ConferenceBody, ConferenceBody.Builder> implements
      // @@protoc_insertion_point(message_implements:easemob.pb.ConferenceBody)
      ConferenceBodyOrBuilder {
    private ConferenceBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      sessionId_ = "";
      operation_ = 0;
      conferenceId_ = "";
      type_ = 0;
      content_ = "";
      network_ = "";
      version_ = "";
      identity_ = 0;
      duration_ = "";
      peerName_ = "";
      endReason_ = 0;
      isDirect_ = false;
      controlType_ = 0;
      com.google.protobuf.UnknownFieldSetLite.Builder unknownFields =
          com.google.protobuf.UnknownFieldSetLite.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readString();
              bitField0_ |= 0x00000001;
              sessionId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              easemob.pb.Conferencebody.ConferenceBody.Operation value = easemob.pb.Conferencebody.ConferenceBody.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                operation_ = rawValue;
              }
              break;
            }
            case 26: {
              String s = input.readString();
              bitField0_ |= 0x00000004;
              conferenceId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              easemob.pb.Conferencebody.ConferenceBody.Type value = easemob.pb.Conferencebody.ConferenceBody.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = rawValue;
              }
              break;
            }
            case 42: {
              String s = input.readString();
              bitField0_ |= 0x00000010;
              content_ = s;
              break;
            }
            case 50: {
              String s = input.readString();
              bitField0_ |= 0x00000020;
              network_ = s;
              break;
            }
            case 58: {
              String s = input.readString();
              bitField0_ |= 0x00000040;
              version_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              easemob.pb.Conferencebody.ConferenceBody.Identity value = easemob.pb.Conferencebody.ConferenceBody.Identity.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                identity_ = rawValue;
              }
              break;
            }
            case 74: {
              String s = input.readString();
              bitField0_ |= 0x00000100;
              duration_ = s;
              break;
            }
            case 82: {
              String s = input.readString();
              bitField0_ |= 0x00000200;
              peerName_ = s;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();
              easemob.pb.Conferencebody.ConferenceBody.EndReason value = easemob.pb.Conferencebody.ConferenceBody.EndReason.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(11, rawValue);
              } else {
                bitField0_ |= 0x00000400;
                endReason_ = rawValue;
              }
              break;
            }
            case 98: {
              easemob.pb.Conferencebody.ConferenceBody.Status.Builder subBuilder = null;
              if (((bitField0_ & 0x00000800) == 0x00000800)) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(easemob.pb.Conferencebody.ConferenceBody.Status.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000800;
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              isDirect_ = input.readBool();
              break;
            }
            case 112: {
              int rawValue = input.readEnum();
              easemob.pb.Conferencebody.ConferenceBody.StreamControlType value = easemob.pb.Conferencebody.ConferenceBody.StreamControlType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(14, rawValue);
              } else {
                bitField0_ |= 0x00002000;
                controlType_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
      }
    }
    /**
     * Protobuf enum {@code easemob.pb.ConferenceBody.Operation}
     */
    public enum Operation
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>JOIN = 0;</code>
       *
       * <pre>
       *join conference
       * </pre>
       */
      JOIN(0, 0),
      /**
       * <code>INITIATE = 1;</code>
       *
       * <pre>
       *initiate call conference
       * </pre>
       */
      INITIATE(1, 1),
      /**
       * <code>ACCEPT_INITIATE = 2;</code>
       *
       * <pre>
       *accept initiate conference
       * </pre>
       */
      ACCEPT_INITIATE(2, 2),
      /**
       * <code>ANSWER = 3;</code>
       *
       * <pre>
       *answer call conference
       * </pre>
       */
      ANSWER(3, 3),
      /**
       * <code>TERMINATE = 4;</code>
       *
       * <pre>
       *terminate call conference
       * </pre>
       */
      TERMINATE(4, 4),
      /**
       * <code>REMOVE = 5;</code>
       *
       * <pre>
       *remove conference
       * </pre>
       */
      REMOVE(5, 5),
      /**
       * <code>STREAM_CONTROL = 6;</code>
       */
      STREAM_CONTROL(6, 6),
      ;

      /**
       * <code>JOIN = 0;</code>
       *
       * <pre>
       *join conference
       * </pre>
       */
      public static final int JOIN_VALUE = 0;
      /**
       * <code>INITIATE = 1;</code>
       *
       * <pre>
       *initiate call conference
       * </pre>
       */
      public static final int INITIATE_VALUE = 1;
      /**
       * <code>ACCEPT_INITIATE = 2;</code>
       *
       * <pre>
       *accept initiate conference
       * </pre>
       */
      public static final int ACCEPT_INITIATE_VALUE = 2;
      /**
       * <code>ANSWER = 3;</code>
       *
       * <pre>
       *answer call conference
       * </pre>
       */
      public static final int ANSWER_VALUE = 3;
      /**
       * <code>TERMINATE = 4;</code>
       *
       * <pre>
       *terminate call conference
       * </pre>
       */
      public static final int TERMINATE_VALUE = 4;
      /**
       * <code>REMOVE = 5;</code>
       *
       * <pre>
       *remove conference
       * </pre>
       */
      public static final int REMOVE_VALUE = 5;
      /**
       * <code>STREAM_CONTROL = 6;</code>
       */
      public static final int STREAM_CONTROL_VALUE = 6;


      public final int getNumber() {
        return value;
      }

      public static Operation valueOf(int value) {
        switch (value) {
          case 0: return JOIN;
          case 1: return INITIATE;
          case 2: return ACCEPT_INITIATE;
          case 3: return ANSWER;
          case 4: return TERMINATE;
          case 5: return REMOVE;
          case 6: return STREAM_CONTROL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number);
              }
            };

      private final int value;

      private Operation(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.ConferenceBody.Operation)
    }

    /**
     * Protobuf enum {@code easemob.pb.ConferenceBody.Type}
     */
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>VOICE = 0;</code>
       *
       * <pre>
       *voice
       * </pre>
       */
      VOICE(0, 0),
      /**
       * <code>VIDEO = 1;</code>
       *
       * <pre>
       *video
       * </pre>
       */
      VIDEO(1, 1),
      ;

      /**
       * <code>VOICE = 0;</code>
       *
       * <pre>
       *voice
       * </pre>
       */
      public static final int VOICE_VALUE = 0;
      /**
       * <code>VIDEO = 1;</code>
       *
       * <pre>
       *video
       * </pre>
       */
      public static final int VIDEO_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return VOICE;
          case 1: return VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      private final int value;

      private Type(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.ConferenceBody.Type)
    }

    /**
     * Protobuf enum {@code easemob.pb.ConferenceBody.Identity}
     */
    public enum Identity
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>CALLER = 0;</code>
       */
      CALLER(0, 0),
      /**
       * <code>CALLEE = 1;</code>
       */
      CALLEE(1, 1),
      ;

      /**
       * <code>CALLER = 0;</code>
       */
      public static final int CALLER_VALUE = 0;
      /**
       * <code>CALLEE = 1;</code>
       */
      public static final int CALLEE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static Identity valueOf(int value) {
        switch (value) {
          case 0: return CALLER;
          case 1: return CALLEE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Identity>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Identity> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Identity>() {
              public Identity findValueByNumber(int number) {
                return Identity.valueOf(number);
              }
            };

      private final int value;

      private Identity(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.ConferenceBody.Identity)
    }

    /**
     * Protobuf enum {@code easemob.pb.ConferenceBody.EndReason}
     */
    public enum EndReason
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>HANGUP = 0;</code>
       *
       * <pre>
       *hang up
       * </pre>
       */
      HANGUP(0, 0),
      /**
       * <code>NORESPONSE = 1;</code>
       *
       * <pre>
       *no response
       * </pre>
       */
      NORESPONSE(1, 1),
      /**
       * <code>REJECT = 2;</code>
       *
       * <pre>
       *reject
       * </pre>
       */
      REJECT(2, 2),
      /**
       * <code>BUSY = 3;</code>
       *
       * <pre>
       *busy
       * </pre>
       */
      BUSY(3, 3),
      /**
       * <code>FAIL = 4;</code>
       *
       * <pre>
       *fail
       * </pre>
       */
      FAIL(4, 4),
      ;

      /**
       * <code>HANGUP = 0;</code>
       *
       * <pre>
       *hang up
       * </pre>
       */
      public static final int HANGUP_VALUE = 0;
      /**
       * <code>NORESPONSE = 1;</code>
       *
       * <pre>
       *no response
       * </pre>
       */
      public static final int NORESPONSE_VALUE = 1;
      /**
       * <code>REJECT = 2;</code>
       *
       * <pre>
       *reject
       * </pre>
       */
      public static final int REJECT_VALUE = 2;
      /**
       * <code>BUSY = 3;</code>
       *
       * <pre>
       *busy
       * </pre>
       */
      public static final int BUSY_VALUE = 3;
      /**
       * <code>FAIL = 4;</code>
       *
       * <pre>
       *fail
       * </pre>
       */
      public static final int FAIL_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      public static EndReason valueOf(int value) {
        switch (value) {
          case 0: return HANGUP;
          case 1: return NORESPONSE;
          case 2: return REJECT;
          case 3: return BUSY;
          case 4: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EndReason>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EndReason> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EndReason>() {
              public EndReason findValueByNumber(int number) {
                return EndReason.valueOf(number);
              }
            };

      private final int value;

      private EndReason(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.ConferenceBody.EndReason)
    }

    /**
     * Protobuf enum {@code easemob.pb.ConferenceBody.StreamControlType}
     */
    public enum StreamControlType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>PAUSE_VOICE = 0;</code>
       */
      PAUSE_VOICE(0, 0),
      /**
       * <code>RESUME_VOICE = 1;</code>
       */
      RESUME_VOICE(1, 1),
      /**
       * <code>PAUSE_VIDEO = 2;</code>
       */
      PAUSE_VIDEO(2, 2),
      /**
       * <code>RESUME_VIDEO = 3;</code>
       */
      RESUME_VIDEO(3, 3),
      ;

      /**
       * <code>PAUSE_VOICE = 0;</code>
       */
      public static final int PAUSE_VOICE_VALUE = 0;
      /**
       * <code>RESUME_VOICE = 1;</code>
       */
      public static final int RESUME_VOICE_VALUE = 1;
      /**
       * <code>PAUSE_VIDEO = 2;</code>
       */
      public static final int PAUSE_VIDEO_VALUE = 2;
      /**
       * <code>RESUME_VIDEO = 3;</code>
       */
      public static final int RESUME_VIDEO_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      public static StreamControlType valueOf(int value) {
        switch (value) {
          case 0: return PAUSE_VOICE;
          case 1: return RESUME_VOICE;
          case 2: return PAUSE_VIDEO;
          case 3: return RESUME_VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StreamControlType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StreamControlType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StreamControlType>() {
              public StreamControlType findValueByNumber(int number) {
                return StreamControlType.valueOf(number);
              }
            };

      private final int value;

      private StreamControlType(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.ConferenceBody.StreamControlType)
    }

    public interface StatusOrBuilder extends
        // @@protoc_insertion_point(interface_extends:easemob.pb.ConferenceBody.Status)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional int32 error_code = 1;</code>
       */
      boolean hasErrorCode();
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      int getErrorCode();
    }
    /**
     * Protobuf type {@code easemob.pb.ConferenceBody.Status}
     */
    public  static final class Status extends
        com.google.protobuf.GeneratedMessageLite<
            Status, Status.Builder> implements
        // @@protoc_insertion_point(message_implements:easemob.pb.ConferenceBody.Status)
        StatusOrBuilder {
      private Status(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        errorCode_ = 0;
        com.google.protobuf.UnknownFieldSetLite.Builder unknownFields =
            com.google.protobuf.UnknownFieldSetLite.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                errorCode_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
        }
      }
      private int bitField0_;
      public static final int ERROR_CODE_FIELD_NUMBER = 1;
      private int errorCode_;
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      private void setErrorCode(int value) {
        bitField0_ |= 0x00000001;
        errorCode_ = value;
      }
      /**
       * <code>optional int32 error_code = 1;</code>
       */
      private void clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, errorCode_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, errorCode_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return parser().parseFrom(data);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return parser().parseFrom(data, extensionRegistry);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return parser().parseFrom(data);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return parser().parseFrom(data, extensionRegistry);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parser().parseFrom(input);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parser().parseFrom(input, extensionRegistry);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parser().parseDelimitedFrom(input);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parser().parseDelimitedFrom(input, extensionRegistry);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return parser().parseFrom(input);
      }
      public static easemob.pb.Conferencebody.ConferenceBody.Status parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parser().parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(easemob.pb.Conferencebody.ConferenceBody.Status prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code easemob.pb.ConferenceBody.Status}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            easemob.pb.Conferencebody.ConferenceBody.Status, Builder> implements
          // @@protoc_insertion_point(builder_implements:easemob.pb.ConferenceBody.Status)
          easemob.pb.Conferencebody.ConferenceBody.StatusOrBuilder {
        // Construct using easemob.pb.Conferencebody.ConferenceBody.Status.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional int32 error_code = 1;</code>
         */
        public boolean hasErrorCode() {
          return instance.hasErrorCode();
        }
        /**
         * <code>optional int32 error_code = 1;</code>
         */
        public int getErrorCode() {
          return instance.getErrorCode();
        }
        /**
         * <code>optional int32 error_code = 1;</code>
         */
        public Builder setErrorCode(int value) {
          copyOnWrite();
          instance.setErrorCode(value);
          return this;
        }
        /**
         * <code>optional int32 error_code = 1;</code>
         */
        public Builder clearErrorCode() {
          copyOnWrite();
          instance.clearErrorCode();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:easemob.pb.ConferenceBody.Status)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case PARSE_PARTIAL_FROM: {
            return new easemob.pb.Conferencebody.ConferenceBody.Status(          (com.google.protobuf.CodedInputStream) arg0,
                (com.google.protobuf.ExtensionRegistryLite) arg1);
          }
          case NEW_INSTANCE: {
            return new easemob.pb.Conferencebody.ConferenceBody.Status(
                com.google.protobuf.Internal.EMPTY_CODED_INPUT_STREAM,
                com.google.protobuf.ExtensionRegistryLite
                    .getEmptyRegistry());
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case MERGE_FROM: {
            if (arg0 == easemob.pb.Conferencebody.ConferenceBody.Status.getDefaultInstance()) return this;
            easemob.pb.Conferencebody.ConferenceBody.Status other = (easemob.pb.Conferencebody.ConferenceBody.Status) arg0;
            if (other.hasErrorCode()) {
              setErrorCode(other.getErrorCode());
            }
            this.mergeUnknownFields(other.unknownFields);
            return this;
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (easemob.pb.Conferencebody.ConferenceBody.Status.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:easemob.pb.ConferenceBody.Status)
      private static final easemob.pb.Conferencebody.ConferenceBody.Status DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Status(
            com.google.protobuf.Internal
                .EMPTY_CODED_INPUT_STREAM,
            com.google.protobuf.ExtensionRegistryLite
                .getEmptyRegistry());
      }

      public static easemob.pb.Conferencebody.ConferenceBody.Status getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Status> PARSER;

      public static com.google.protobuf.Parser<Status> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private java.lang.String sessionId_;
    /**
     * <code>optional string session_id = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    public java.lang.String getSessionId() {
      return sessionId_;
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sessionId_);
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    private void setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      sessionId_ = value;
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    private void clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = getDefaultInstance().getSessionId();
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    private void setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      sessionId_ = value.toStringUtf8();
    }

    public static final int OPERATION_FIELD_NUMBER = 2;
    private int operation_;
    /**
     * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
     */
    public easemob.pb.Conferencebody.ConferenceBody.Operation getOperation() {
      easemob.pb.Conferencebody.ConferenceBody.Operation result = easemob.pb.Conferencebody.ConferenceBody.Operation.valueOf(operation_);
      return result == null ? easemob.pb.Conferencebody.ConferenceBody.Operation.JOIN : result;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
     */
    private void setOperation(easemob.pb.Conferencebody.ConferenceBody.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      operation_ = value.getNumber();
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
     */
    private void clearOperation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      operation_ = 0;
    }

    public static final int CONFERENCE_ID_FIELD_NUMBER = 3;
    private java.lang.String conferenceId_;
    /**
     * <code>optional string conference_id = 3;</code>
     */
    public boolean hasConferenceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string conference_id = 3;</code>
     */
    public java.lang.String getConferenceId() {
      return conferenceId_;
    }
    /**
     * <code>optional string conference_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getConferenceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(conferenceId_);
    }
    /**
     * <code>optional string conference_id = 3;</code>
     */
    private void setConferenceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      conferenceId_ = value;
    }
    /**
     * <code>optional string conference_id = 3;</code>
     */
    private void clearConferenceId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      conferenceId_ = getDefaultInstance().getConferenceId();
    }
    /**
     * <code>optional string conference_id = 3;</code>
     */
    private void setConferenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      conferenceId_ = value.toStringUtf8();
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
     */
    public easemob.pb.Conferencebody.ConferenceBody.Type getType() {
      easemob.pb.Conferencebody.ConferenceBody.Type result = easemob.pb.Conferencebody.ConferenceBody.Type.valueOf(type_);
      return result == null ? easemob.pb.Conferencebody.ConferenceBody.Type.VOICE : result;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
     */
    private void setType(easemob.pb.Conferencebody.ConferenceBody.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      type_ = value.getNumber();
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
     */
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = 0;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private java.lang.String content_;
    /**
     * <code>optional string content = 5;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string content = 5;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>optional string content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>optional string content = 5;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      content_ = value;
    }
    /**
     * <code>optional string content = 5;</code>
     */
    private void clearContent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>optional string content = 5;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      content_ = value.toStringUtf8();
    }

    public static final int NETWORK_FIELD_NUMBER = 6;
    private java.lang.String network_;
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    public boolean hasNetwork() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    public java.lang.String getNetwork() {
      return network_;
    }
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(network_);
    }
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    private void setNetwork(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      network_ = value;
    }
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    private void clearNetwork() {
      bitField0_ = (bitField0_ & ~0x00000020);
      network_ = getDefaultInstance().getNetwork();
    }
    /**
     * <code>optional string network = 6;</code>
     *
     * <pre>
     *statistics
     * </pre>
     */
    private void setNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      network_ = value.toStringUtf8();
    }

    public static final int VERSION_FIELD_NUMBER = 7;
    private java.lang.String version_;
    /**
     * <code>optional string version = 7;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string version = 7;</code>
     */
    public java.lang.String getVersion() {
      return version_;
    }
    /**
     * <code>optional string version = 7;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(version_);
    }
    /**
     * <code>optional string version = 7;</code>
     */
    private void setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      version_ = value;
    }
    /**
     * <code>optional string version = 7;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000040);
      version_ = getDefaultInstance().getVersion();
    }
    /**
     * <code>optional string version = 7;</code>
     */
    private void setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      version_ = value.toStringUtf8();
    }

    public static final int IDENTITY_FIELD_NUMBER = 8;
    private int identity_;
    /**
     * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
     */
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
     */
    public easemob.pb.Conferencebody.ConferenceBody.Identity getIdentity() {
      easemob.pb.Conferencebody.ConferenceBody.Identity result = easemob.pb.Conferencebody.ConferenceBody.Identity.valueOf(identity_);
      return result == null ? easemob.pb.Conferencebody.ConferenceBody.Identity.CALLER : result;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
     */
    private void setIdentity(easemob.pb.Conferencebody.ConferenceBody.Identity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      identity_ = value.getNumber();
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
     */
    private void clearIdentity() {
      bitField0_ = (bitField0_ & ~0x00000080);
      identity_ = 0;
    }

    public static final int DURATION_FIELD_NUMBER = 9;
    private java.lang.String duration_;
    /**
     * <code>optional string duration = 9;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string duration = 9;</code>
     */
    public java.lang.String getDuration() {
      return duration_;
    }
    /**
     * <code>optional string duration = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDurationBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(duration_);
    }
    /**
     * <code>optional string duration = 9;</code>
     */
    private void setDuration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      duration_ = value;
    }
    /**
     * <code>optional string duration = 9;</code>
     */
    private void clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000100);
      duration_ = getDefaultInstance().getDuration();
    }
    /**
     * <code>optional string duration = 9;</code>
     */
    private void setDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      duration_ = value.toStringUtf8();
    }

    public static final int PEER_NAME_FIELD_NUMBER = 10;
    private java.lang.String peerName_;
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    public boolean hasPeerName() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    public java.lang.String getPeerName() {
      return peerName_;
    }
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(peerName_);
    }
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    private void setPeerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      peerName_ = value;
    }
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    private void clearPeerName() {
      bitField0_ = (bitField0_ & ~0x00000200);
      peerName_ = getDefaultInstance().getPeerName();
    }
    /**
     * <code>optional string peer_name = 10;</code>
     *
     * <pre>
     *join
     * </pre>
     */
    private void setPeerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      peerName_ = value.toStringUtf8();
    }

    public static final int END_REASON_FIELD_NUMBER = 11;
    private int endReason_;
    /**
     * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
     *
     * <pre>
     *terminate
     * </pre>
     */
    public boolean hasEndReason() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
     *
     * <pre>
     *terminate
     * </pre>
     */
    public easemob.pb.Conferencebody.ConferenceBody.EndReason getEndReason() {
      easemob.pb.Conferencebody.ConferenceBody.EndReason result = easemob.pb.Conferencebody.ConferenceBody.EndReason.valueOf(endReason_);
      return result == null ? easemob.pb.Conferencebody.ConferenceBody.EndReason.HANGUP : result;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
     *
     * <pre>
     *terminate
     * </pre>
     */
    private void setEndReason(easemob.pb.Conferencebody.ConferenceBody.EndReason value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000400;
      endReason_ = value.getNumber();
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
     *
     * <pre>
     *terminate
     * </pre>
     */
    private void clearEndReason() {
      bitField0_ = (bitField0_ & ~0x00000400);
      endReason_ = 0;
    }

    public static final int STATUS_FIELD_NUMBER = 12;
    private easemob.pb.Conferencebody.ConferenceBody.Status status_;
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    public easemob.pb.Conferencebody.ConferenceBody.Status getStatus() {
      return status_ == null ? easemob.pb.Conferencebody.ConferenceBody.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    private void setStatus(easemob.pb.Conferencebody.ConferenceBody.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      status_ = value;
      bitField0_ |= 0x00000800;
      }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    private void setStatus(
        easemob.pb.Conferencebody.ConferenceBody.Status.Builder builderForValue) {
      status_ = builderForValue.build();
      bitField0_ |= 0x00000800;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    private void mergeStatus(easemob.pb.Conferencebody.ConferenceBody.Status value) {
      if (status_ != null &&
          status_ != easemob.pb.Conferencebody.ConferenceBody.Status.getDefaultInstance()) {
        status_ =
          easemob.pb.Conferencebody.ConferenceBody.Status.newBuilder(status_).mergeFrom(value).buildPartial();
      } else {
        status_ = value;
      }
      bitField0_ |= 0x00000800;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
     *
     * <pre>
     *error
     * </pre>
     */
    private void clearStatus() {  status_ = null;
      bitField0_ = (bitField0_ & ~0x00000800);
    }

    public static final int IS_DIRECT_FIELD_NUMBER = 13;
    private boolean isDirect_;
    /**
     * <code>optional bool is_direct = 13;</code>
     *
     * <pre>
     *stream update
     * </pre>
     */
    public boolean hasIsDirect() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bool is_direct = 13;</code>
     *
     * <pre>
     *stream update
     * </pre>
     */
    public boolean getIsDirect() {
      return isDirect_;
    }
    /**
     * <code>optional bool is_direct = 13;</code>
     *
     * <pre>
     *stream update
     * </pre>
     */
    private void setIsDirect(boolean value) {
      bitField0_ |= 0x00001000;
      isDirect_ = value;
    }
    /**
     * <code>optional bool is_direct = 13;</code>
     *
     * <pre>
     *stream update
     * </pre>
     */
    private void clearIsDirect() {
      bitField0_ = (bitField0_ & ~0x00001000);
      isDirect_ = false;
    }

    public static final int CONTROL_TYPE_FIELD_NUMBER = 14;
    private int controlType_;
    /**
     * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
     */
    public boolean hasControlType() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
     */
    public easemob.pb.Conferencebody.ConferenceBody.StreamControlType getControlType() {
      easemob.pb.Conferencebody.ConferenceBody.StreamControlType result = easemob.pb.Conferencebody.ConferenceBody.StreamControlType.valueOf(controlType_);
      return result == null ? easemob.pb.Conferencebody.ConferenceBody.StreamControlType.PAUSE_VOICE : result;
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
     */
    private void setControlType(easemob.pb.Conferencebody.ConferenceBody.StreamControlType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00002000;
      controlType_ = value.getNumber();
    }
    /**
     * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
     */
    private void clearControlType() {
      bitField0_ = (bitField0_ & ~0x00002000);
      controlType_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getSessionId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, operation_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getConferenceId());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeString(5, getContent());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeString(6, getNetwork());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeString(7, getVersion());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, identity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeString(9, getDuration());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeString(10, getPeerName());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeEnum(11, endReason_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(12, getStatus());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(13, isDirect_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeEnum(14, controlType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSessionId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, operation_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getConferenceId());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getContent());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getNetwork());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getVersion());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, identity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getDuration());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getPeerName());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, endReason_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getStatus());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, isDirect_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(14, controlType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parser().parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseDelimitedFrom(input, extensionRegistry);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return parser().parseFrom(input);
    }
    public static easemob.pb.Conferencebody.ConferenceBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parser().parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(easemob.pb.Conferencebody.ConferenceBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code easemob.pb.ConferenceBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          easemob.pb.Conferencebody.ConferenceBody, Builder> implements
        // @@protoc_insertion_point(builder_implements:easemob.pb.ConferenceBody)
        easemob.pb.Conferencebody.ConferenceBodyOrBuilder {
      // Construct using easemob.pb.Conferencebody.ConferenceBody.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string session_id = 1;</code>
       */
      public boolean hasSessionId() {
        return instance.hasSessionId();
      }
      /**
       * <code>optional string session_id = 1;</code>
       */
      public java.lang.String getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <code>optional string session_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        return instance.getSessionIdBytes();
      }
      /**
       * <code>optional string session_id = 1;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <code>optional string session_id = 1;</code>
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }
      /**
       * <code>optional string session_id = 1;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSessionIdBytes(value);
        return this;
      }

      /**
       * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
       */
      public boolean hasOperation() {
        return instance.hasOperation();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
       */
      public easemob.pb.Conferencebody.ConferenceBody.Operation getOperation() {
        return instance.getOperation();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
       */
      public Builder setOperation(easemob.pb.Conferencebody.ConferenceBody.Operation value) {
        copyOnWrite();
        instance.setOperation(value);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Operation operation = 2;</code>
       */
      public Builder clearOperation() {
        copyOnWrite();
        instance.clearOperation();
        return this;
      }

      /**
       * <code>optional string conference_id = 3;</code>
       */
      public boolean hasConferenceId() {
        return instance.hasConferenceId();
      }
      /**
       * <code>optional string conference_id = 3;</code>
       */
      public java.lang.String getConferenceId() {
        return instance.getConferenceId();
      }
      /**
       * <code>optional string conference_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getConferenceIdBytes() {
        return instance.getConferenceIdBytes();
      }
      /**
       * <code>optional string conference_id = 3;</code>
       */
      public Builder setConferenceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setConferenceId(value);
        return this;
      }
      /**
       * <code>optional string conference_id = 3;</code>
       */
      public Builder clearConferenceId() {
        copyOnWrite();
        instance.clearConferenceId();
        return this;
      }
      /**
       * <code>optional string conference_id = 3;</code>
       */
      public Builder setConferenceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setConferenceIdBytes(value);
        return this;
      }

      /**
       * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
       */
      public boolean hasType() {
        return instance.hasType();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
       */
      public easemob.pb.Conferencebody.ConferenceBody.Type getType() {
        return instance.getType();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
       */
      public Builder setType(easemob.pb.Conferencebody.ConferenceBody.Type value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Type type = 4;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>optional string content = 5;</code>
       */
      public boolean hasContent() {
        return instance.hasContent();
      }
      /**
       * <code>optional string content = 5;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>optional string content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>optional string content = 5;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <code>optional string network = 6;</code>
       *
       * <pre>
       *statistics
       * </pre>
       */
      public boolean hasNetwork() {
        return instance.hasNetwork();
      }
      /**
       * <code>optional string network = 6;</code>
       *
       * <pre>
       *statistics
       * </pre>
       */
      public java.lang.String getNetwork() {
        return instance.getNetwork();
      }
      /**
       * <code>optional string network = 6;</code>
       *
       * <pre>
       *statistics
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNetworkBytes() {
        return instance.getNetworkBytes();
      }
      /**
       * <code>optional string network = 6;</code>
       *
       * <pre>
       *statistics
       * </pre>
       */
      public Builder setNetwork(
          java.lang.String value) {
        copyOnWrite();
        instance.setNetwork(value);
        return this;
      }
      /**
       * <code>optional string network = 6;</code>
       *
       * <pre>
       *statistics
       * </pre>
       */
      public Builder clearNetwork() {
        copyOnWrite();
        instance.clearNetwork();
        return this;
      }
      /**
       * <code>optional string network = 6;</code>
       *
       * <pre>
       *statistics
       * </pre>
       */
      public Builder setNetworkBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNetworkBytes(value);
        return this;
      }

      /**
       * <code>optional string version = 7;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public java.lang.String getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        return instance.getVersionBytes();
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }
      /**
       * <code>optional string version = 7;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVersionBytes(value);
        return this;
      }

      /**
       * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
       */
      public boolean hasIdentity() {
        return instance.hasIdentity();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
       */
      public easemob.pb.Conferencebody.ConferenceBody.Identity getIdentity() {
        return instance.getIdentity();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
       */
      public Builder setIdentity(easemob.pb.Conferencebody.ConferenceBody.Identity value) {
        copyOnWrite();
        instance.setIdentity(value);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Identity identity = 8;</code>
       */
      public Builder clearIdentity() {
        copyOnWrite();
        instance.clearIdentity();
        return this;
      }

      /**
       * <code>optional string duration = 9;</code>
       */
      public boolean hasDuration() {
        return instance.hasDuration();
      }
      /**
       * <code>optional string duration = 9;</code>
       */
      public java.lang.String getDuration() {
        return instance.getDuration();
      }
      /**
       * <code>optional string duration = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDurationBytes() {
        return instance.getDurationBytes();
      }
      /**
       * <code>optional string duration = 9;</code>
       */
      public Builder setDuration(
          java.lang.String value) {
        copyOnWrite();
        instance.setDuration(value);
        return this;
      }
      /**
       * <code>optional string duration = 9;</code>
       */
      public Builder clearDuration() {
        copyOnWrite();
        instance.clearDuration();
        return this;
      }
      /**
       * <code>optional string duration = 9;</code>
       */
      public Builder setDurationBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDurationBytes(value);
        return this;
      }

      /**
       * <code>optional string peer_name = 10;</code>
       *
       * <pre>
       *join
       * </pre>
       */
      public boolean hasPeerName() {
        return instance.hasPeerName();
      }
      /**
       * <code>optional string peer_name = 10;</code>
       *
       * <pre>
       *join
       * </pre>
       */
      public java.lang.String getPeerName() {
        return instance.getPeerName();
      }
      /**
       * <code>optional string peer_name = 10;</code>
       *
       * <pre>
       *join
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        return instance.getPeerNameBytes();
      }
      /**
       * <code>optional string peer_name = 10;</code>
       *
       * <pre>
       *join
       * </pre>
       */
      public Builder setPeerName(
          java.lang.String value) {
        copyOnWrite();
        instance.setPeerName(value);
        return this;
      }
      /**
       * <code>optional string peer_name = 10;</code>
       *
       * <pre>
       *join
       * </pre>
       */
      public Builder clearPeerName() {
        copyOnWrite();
        instance.clearPeerName();
        return this;
      }
      /**
       * <code>optional string peer_name = 10;</code>
       *
       * <pre>
       *join
       * </pre>
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPeerNameBytes(value);
        return this;
      }

      /**
       * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
       *
       * <pre>
       *terminate
       * </pre>
       */
      public boolean hasEndReason() {
        return instance.hasEndReason();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
       *
       * <pre>
       *terminate
       * </pre>
       */
      public easemob.pb.Conferencebody.ConferenceBody.EndReason getEndReason() {
        return instance.getEndReason();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
       *
       * <pre>
       *terminate
       * </pre>
       */
      public Builder setEndReason(easemob.pb.Conferencebody.ConferenceBody.EndReason value) {
        copyOnWrite();
        instance.setEndReason(value);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.EndReason end_reason = 11;</code>
       *
       * <pre>
       *terminate
       * </pre>
       */
      public Builder clearEndReason() {
        copyOnWrite();
        instance.clearEndReason();
        return this;
      }

      /**
       * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
       *
       * <pre>
       *error
       * </pre>
       */
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
       *
       * <pre>
       *error
       * </pre>
       */
      public easemob.pb.Conferencebody.ConferenceBody.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
       *
       * <pre>
       *error
       * </pre>
       */
      public Builder setStatus(easemob.pb.Conferencebody.ConferenceBody.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
        }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
       *
       * <pre>
       *error
       * </pre>
       */
      public Builder setStatus(
          easemob.pb.Conferencebody.ConferenceBody.Status.Builder builderForValue) {
        copyOnWrite();
        instance.setStatus(builderForValue);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
       *
       * <pre>
       *error
       * </pre>
       */
      public Builder mergeStatus(easemob.pb.Conferencebody.ConferenceBody.Status value) {
        copyOnWrite();
        instance.mergeStatus(value);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.Status status = 12;</code>
       *
       * <pre>
       *error
       * </pre>
       */
      public Builder clearStatus() {  copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>optional bool is_direct = 13;</code>
       *
       * <pre>
       *stream update
       * </pre>
       */
      public boolean hasIsDirect() {
        return instance.hasIsDirect();
      }
      /**
       * <code>optional bool is_direct = 13;</code>
       *
       * <pre>
       *stream update
       * </pre>
       */
      public boolean getIsDirect() {
        return instance.getIsDirect();
      }
      /**
       * <code>optional bool is_direct = 13;</code>
       *
       * <pre>
       *stream update
       * </pre>
       */
      public Builder setIsDirect(boolean value) {
        copyOnWrite();
        instance.setIsDirect(value);
        return this;
      }
      /**
       * <code>optional bool is_direct = 13;</code>
       *
       * <pre>
       *stream update
       * </pre>
       */
      public Builder clearIsDirect() {
        copyOnWrite();
        instance.clearIsDirect();
        return this;
      }

      /**
       * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
       */
      public boolean hasControlType() {
        return instance.hasControlType();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
       */
      public easemob.pb.Conferencebody.ConferenceBody.StreamControlType getControlType() {
        return instance.getControlType();
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
       */
      public Builder setControlType(easemob.pb.Conferencebody.ConferenceBody.StreamControlType value) {
        copyOnWrite();
        instance.setControlType(value);
        return this;
      }
      /**
       * <code>optional .easemob.pb.ConferenceBody.StreamControlType control_type = 14;</code>
       */
      public Builder clearControlType() {
        copyOnWrite();
        instance.clearControlType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:easemob.pb.ConferenceBody)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case PARSE_PARTIAL_FROM: {
          return new easemob.pb.Conferencebody.ConferenceBody(          (com.google.protobuf.CodedInputStream) arg0,
              (com.google.protobuf.ExtensionRegistryLite) arg1);
        }
        case NEW_INSTANCE: {
          return new easemob.pb.Conferencebody.ConferenceBody(
              com.google.protobuf.Internal.EMPTY_CODED_INPUT_STREAM,
              com.google.protobuf.ExtensionRegistryLite
                  .getEmptyRegistry());
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case MERGE_FROM: {
          if (arg0 == easemob.pb.Conferencebody.ConferenceBody.getDefaultInstance()) return this;
          easemob.pb.Conferencebody.ConferenceBody other = (easemob.pb.Conferencebody.ConferenceBody) arg0;
          if (other.hasSessionId()) {
            bitField0_ |= 0x00000001;
            sessionId_ = other.sessionId_;
            
          }
          if (other.hasOperation()) {
            setOperation(other.getOperation());
          }
          if (other.hasConferenceId()) {
            bitField0_ |= 0x00000004;
            conferenceId_ = other.conferenceId_;
            
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasContent()) {
            bitField0_ |= 0x00000010;
            content_ = other.content_;
            
          }
          if (other.hasNetwork()) {
            bitField0_ |= 0x00000020;
            network_ = other.network_;
            
          }
          if (other.hasVersion()) {
            bitField0_ |= 0x00000040;
            version_ = other.version_;
            
          }
          if (other.hasIdentity()) {
            setIdentity(other.getIdentity());
          }
          if (other.hasDuration()) {
            bitField0_ |= 0x00000100;
            duration_ = other.duration_;
            
          }
          if (other.hasPeerName()) {
            bitField0_ |= 0x00000200;
            peerName_ = other.peerName_;
            
          }
          if (other.hasEndReason()) {
            setEndReason(other.getEndReason());
          }
          if (other.hasStatus()) {
            mergeStatus(other.getStatus());
          }
          if (other.hasIsDirect()) {
            setIsDirect(other.getIsDirect());
          }
          if (other.hasControlType()) {
            setControlType(other.getControlType());
          }
          this.mergeUnknownFields(other.unknownFields);
          return this;
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (easemob.pb.Conferencebody.ConferenceBody.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:easemob.pb.ConferenceBody)
    private static final easemob.pb.Conferencebody.ConferenceBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ConferenceBody(
          com.google.protobuf.Internal
              .EMPTY_CODED_INPUT_STREAM,
          com.google.protobuf.ExtensionRegistryLite
              .getEmptyRegistry());
    }

    public static easemob.pb.Conferencebody.ConferenceBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ConferenceBody> PARSER;

    public static com.google.protobuf.Parser<ConferenceBody> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
