// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyvalue.proto

package easemob.pb;

public final class Keyvalue {
  private Keyvalue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:easemob.pb.KeyValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
     */
    easemob.pb.Keyvalue.KeyValue.ValueType getType();

    /**
     * <code>optional int64 varint_value = 3;</code>
     */
    boolean hasVarintValue();
    /**
     * <code>optional int64 varint_value = 3;</code>
     */
    long getVarintValue();

    /**
     * <code>optional float float_value = 4;</code>
     */
    boolean hasFloatValue();
    /**
     * <code>optional float float_value = 4;</code>
     */
    float getFloatValue();

    /**
     * <code>optional double double_value = 5;</code>
     */
    boolean hasDoubleValue();
    /**
     * <code>optional double double_value = 5;</code>
     */
    double getDoubleValue();

    /**
     * <code>optional string string_value = 6;</code>
     */
    boolean hasStringValue();
    /**
     * <code>optional string string_value = 6;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string string_value = 6;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    public easemob.pb.Keyvalue.KeyValue.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code easemob.pb.KeyValue}
   */
  public  static final class KeyValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:easemob.pb.KeyValue)
      KeyValueOrBuilder {
    // Use KeyValue.newBuilder() to construct.
    private KeyValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private KeyValue() {
      key_ = "";
      type_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              easemob.pb.Keyvalue.KeyValue.ValueType value = easemob.pb.Keyvalue.KeyValue.ValueType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 24: {
              valueCase_ = 3;
              value_ = input.readInt64();
              break;
            }
            case 37: {
              valueCase_ = 4;
              value_ = input.readFloat();
              break;
            }
            case 41: {
              valueCase_ = 5;
              value_ = input.readDouble();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              valueCase_ = 6;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return easemob.pb.Keyvalue.internal_static_easemob_pb_KeyValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return easemob.pb.Keyvalue.internal_static_easemob_pb_KeyValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              easemob.pb.Keyvalue.KeyValue.class, easemob.pb.Keyvalue.KeyValue.Builder.class);
    }

    /**
     * Protobuf enum {@code easemob.pb.KeyValue.ValueType}
     */
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BOOL = 1;</code>
       */
      BOOL(0, 1),
      /**
       * <code>INT = 2;</code>
       */
      INT(1, 2),
      /**
       * <code>UINT = 3;</code>
       */
      UINT(2, 3),
      /**
       * <code>LLINT = 4;</code>
       */
      LLINT(3, 4),
      /**
       * <code>FLOAT = 5;</code>
       */
      FLOAT(4, 5),
      /**
       * <code>DOUBLE = 6;</code>
       */
      DOUBLE(5, 6),
      /**
       * <code>STRING = 7;</code>
       */
      STRING(6, 7),
      /**
       * <code>JSON_STRING = 8;</code>
       */
      JSON_STRING(7, 8),
      ;

      /**
       * <code>BOOL = 1;</code>
       */
      public static final int BOOL_VALUE = 1;
      /**
       * <code>INT = 2;</code>
       */
      public static final int INT_VALUE = 2;
      /**
       * <code>UINT = 3;</code>
       */
      public static final int UINT_VALUE = 3;
      /**
       * <code>LLINT = 4;</code>
       */
      public static final int LLINT_VALUE = 4;
      /**
       * <code>FLOAT = 5;</code>
       */
      public static final int FLOAT_VALUE = 5;
      /**
       * <code>DOUBLE = 6;</code>
       */
      public static final int DOUBLE_VALUE = 6;
      /**
       * <code>STRING = 7;</code>
       */
      public static final int STRING_VALUE = 7;
      /**
       * <code>JSON_STRING = 8;</code>
       */
      public static final int JSON_STRING_VALUE = 8;


      public final int getNumber() {
        return value;
      }

      public static ValueType valueOf(int value) {
        switch (value) {
          case 1: return BOOL;
          case 2: return INT;
          case 3: return UINT;
          case 4: return LLINT;
          case 5: return FLOAT;
          case 6: return DOUBLE;
          case 7: return STRING;
          case 8: return JSON_STRING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValueType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return easemob.pb.Keyvalue.KeyValue.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValueType[] VALUES = values();

      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ValueType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.KeyValue.ValueType)
    }

    private int bitField0_;
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite {
      VARINT_VALUE(3),
      FLOAT_VALUE(4),
      DOUBLE_VALUE(5),
      STRING_VALUE(6),
      VALUE_NOT_SET(0);
      private int value = 0;
      private ValueCase(int value) {
        this.value = value;
      }
      public static ValueCase valueOf(int value) {
        switch (value) {
          case 3: return VARINT_VALUE;
          case 4: return FLOAT_VALUE;
          case 5: return DOUBLE_VALUE;
          case 6: return STRING_VALUE;
          case 0: return VALUE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.valueOf(
          valueCase_);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
     */
    public easemob.pb.Keyvalue.KeyValue.ValueType getType() {
      easemob.pb.Keyvalue.KeyValue.ValueType result = easemob.pb.Keyvalue.KeyValue.ValueType.valueOf(type_);
      return result == null ? easemob.pb.Keyvalue.KeyValue.ValueType.BOOL : result;
    }

    public static final int VARINT_VALUE_FIELD_NUMBER = 3;
    /**
     * <code>optional int64 varint_value = 3;</code>
     */
    public boolean hasVarintValue() {
      return valueCase_ == 3;
    }
    /**
     * <code>optional int64 varint_value = 3;</code>
     */
    public long getVarintValue() {
      if (valueCase_ == 3) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }

    public static final int FLOAT_VALUE_FIELD_NUMBER = 4;
    /**
     * <code>optional float float_value = 4;</code>
     */
    public boolean hasFloatValue() {
      return valueCase_ == 4;
    }
    /**
     * <code>optional float float_value = 4;</code>
     */
    public float getFloatValue() {
      if (valueCase_ == 4) {
        return (java.lang.Float) value_;
      }
      return 0F;
    }

    public static final int DOUBLE_VALUE_FIELD_NUMBER = 5;
    /**
     * <code>optional double double_value = 5;</code>
     */
    public boolean hasDoubleValue() {
      return valueCase_ == 5;
    }
    /**
     * <code>optional double double_value = 5;</code>
     */
    public double getDoubleValue() {
      if (valueCase_ == 5) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 6;
    /**
     * <code>optional string string_value = 6;</code>
     */
    public boolean hasStringValue() {
      return valueCase_ == 6;
    }
    /**
     * <code>optional string string_value = 6;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueCase_ == 6) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (valueCase_ == 6)) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string_value = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 6) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 6) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      if (valueCase_ == 3) {
        output.writeInt64(
            3, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 4) {
        output.writeFloat(
            4, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 5) {
        output.writeDouble(
            5, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 6) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(
              3, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(
              4, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              5, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 6) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static easemob.pb.Keyvalue.KeyValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static easemob.pb.Keyvalue.KeyValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static easemob.pb.Keyvalue.KeyValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static easemob.pb.Keyvalue.KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(easemob.pb.Keyvalue.KeyValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code easemob.pb.KeyValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:easemob.pb.KeyValue)
        easemob.pb.Keyvalue.KeyValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return easemob.pb.Keyvalue.internal_static_easemob_pb_KeyValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return easemob.pb.Keyvalue.internal_static_easemob_pb_KeyValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                easemob.pb.Keyvalue.KeyValue.class, easemob.pb.Keyvalue.KeyValue.Builder.class);
      }

      // Construct using easemob.pb.Keyvalue.KeyValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return easemob.pb.Keyvalue.internal_static_easemob_pb_KeyValue_descriptor;
      }

      public easemob.pb.Keyvalue.KeyValue getDefaultInstanceForType() {
        return easemob.pb.Keyvalue.KeyValue.getDefaultInstance();
      }

      public easemob.pb.Keyvalue.KeyValue build() {
        easemob.pb.Keyvalue.KeyValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public easemob.pb.Keyvalue.KeyValue buildPartial() {
        easemob.pb.Keyvalue.KeyValue result = new easemob.pb.Keyvalue.KeyValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (valueCase_ == 3) {
          result.value_ = value_;
        }
        if (valueCase_ == 4) {
          result.value_ = value_;
        }
        if (valueCase_ == 5) {
          result.value_ = value_;
        }
        if (valueCase_ == 6) {
          result.value_ = value_;
        }
        result.bitField0_ = to_bitField0_;
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof easemob.pb.Keyvalue.KeyValue) {
          return mergeFrom((easemob.pb.Keyvalue.KeyValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(easemob.pb.Keyvalue.KeyValue other) {
        if (other == easemob.pb.Keyvalue.KeyValue.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        switch (other.getValueCase()) {
          case VARINT_VALUE: {
            setVarintValue(other.getVarintValue());
            break;
          }
          case FLOAT_VALUE: {
            setFloatValue(other.getFloatValue());
            break;
          }
          case DOUBLE_VALUE: {
            setDoubleValue(other.getDoubleValue());
            break;
          }
          case STRING_VALUE: {
            valueCase_ = 6;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        easemob.pb.Keyvalue.KeyValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (easemob.pb.Keyvalue.KeyValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.valueOf(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
       */
      public easemob.pb.Keyvalue.KeyValue.ValueType getType() {
        easemob.pb.Keyvalue.KeyValue.ValueType result = easemob.pb.Keyvalue.KeyValue.ValueType.valueOf(type_);
        return result == null ? easemob.pb.Keyvalue.KeyValue.ValueType.BOOL : result;
      }
      /**
       * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
       */
      public Builder setType(easemob.pb.Keyvalue.KeyValue.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .easemob.pb.KeyValue.ValueType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 1;
        onChanged();
        return this;
      }

      /**
       * <code>optional int64 varint_value = 3;</code>
       */
      public boolean hasVarintValue() {
        return valueCase_ == 3;
      }
      /**
       * <code>optional int64 varint_value = 3;</code>
       */
      public long getVarintValue() {
        if (valueCase_ == 3) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }
      /**
       * <code>optional int64 varint_value = 3;</code>
       */
      public Builder setVarintValue(long value) {
        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 varint_value = 3;</code>
       */
      public Builder clearVarintValue() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional float float_value = 4;</code>
       */
      public boolean hasFloatValue() {
        return valueCase_ == 4;
      }
      /**
       * <code>optional float float_value = 4;</code>
       */
      public float getFloatValue() {
        if (valueCase_ == 4) {
          return (java.lang.Float) value_;
        }
        return 0F;
      }
      /**
       * <code>optional float float_value = 4;</code>
       */
      public Builder setFloatValue(float value) {
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float float_value = 4;</code>
       */
      public Builder clearFloatValue() {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional double double_value = 5;</code>
       */
      public boolean hasDoubleValue() {
        return valueCase_ == 5;
      }
      /**
       * <code>optional double double_value = 5;</code>
       */
      public double getDoubleValue() {
        if (valueCase_ == 5) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>optional double double_value = 5;</code>
       */
      public Builder setDoubleValue(double value) {
        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double double_value = 5;</code>
       */
      public Builder clearDoubleValue() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string string_value = 6;</code>
       */
      public boolean hasStringValue() {
        return valueCase_ == 6;
      }
      /**
       * <code>optional string string_value = 6;</code>
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueCase_ == 6) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 6) {
            if (bs.isValidUtf8()) {
              value_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string_value = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 6) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 6) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string_value = 6;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 6;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_value = 6;</code>
       */
      public Builder clearStringValue() {
        if (valueCase_ == 6) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string string_value = 6;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 6;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:easemob.pb.KeyValue)
    }

    // @@protoc_insertion_point(class_scope:easemob.pb.KeyValue)
    private static final easemob.pb.Keyvalue.KeyValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new easemob.pb.Keyvalue.KeyValue();
    }

    public static easemob.pb.Keyvalue.KeyValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KeyValue>
        PARSER = new com.google.protobuf.AbstractParser<KeyValue>() {
      public KeyValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new KeyValue(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<KeyValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValue> getParserForType() {
      return PARSER;
    }

    public easemob.pb.Keyvalue.KeyValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_easemob_pb_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_easemob_pb_KeyValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016keyvalue.proto\022\neasemob.pb\"\226\002\n\010KeyValu" +
      "e\022\013\n\003key\030\001 \001(\t\022,\n\004type\030\002 \001(\0162\036.easemob.p" +
      "b.KeyValue.ValueType\022\026\n\014varint_value\030\003 \001" +
      "(\003H\000\022\025\n\013float_value\030\004 \001(\002H\000\022\026\n\014double_va" +
      "lue\030\005 \001(\001H\000\022\026\n\014string_value\030\006 \001(\tH\000\"g\n\tV" +
      "alueType\022\010\n\004BOOL\020\001\022\007\n\003INT\020\002\022\010\n\004UINT\020\003\022\t\n" +
      "\005LLINT\020\004\022\t\n\005FLOAT\020\005\022\n\n\006DOUBLE\020\006\022\n\n\006STRIN" +
      "G\020\007\022\017\n\013JSON_STRING\020\010B\007\n\005value"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_easemob_pb_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_easemob_pb_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_easemob_pb_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Type", "VarintValue", "FloatValue", "DoubleValue", "StringValue", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
