// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rosterbody.proto

package easemob.pb;

public final class Rosterbody {
  private Rosterbody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RosterBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:easemob.pb.RosterBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
     */
    boolean hasOperation();
    /**
     * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
     */
    easemob.pb.Rosterbody.RosterBody.Operation getOperation();

    /**
     * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
     *
     * <pre>
     *server send to client this error with original operation id if some operation met error
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
     *
     * <pre>
     *server send to client this error with original operation id if some operation met error
     * </pre>
     */
    easemob.pb.Rosterbody.RosterBody.Status getStatus();
    /**
     * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
     *
     * <pre>
     *server send to client this error with original operation id if some operation met error
     * </pre>
     */
    easemob.pb.Rosterbody.RosterBody.StatusOrBuilder getStatusOrBuilder();

    /**
     * <code>optional .easemob.pb.JID from = 3;</code>
     */
    boolean hasFrom();
    /**
     * <code>optional .easemob.pb.JID from = 3;</code>
     */
    easemob.pb.Jid.JID getFrom();
    /**
     * <code>optional .easemob.pb.JID from = 3;</code>
     */
    easemob.pb.Jid.JIDOrBuilder getFromOrBuilder();

    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    java.util.List<easemob.pb.Jid.JID> 
        getToList();
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    easemob.pb.Jid.JID getTo(int index);
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    int getToCount();
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    java.util.List<? extends easemob.pb.Jid.JIDOrBuilder> 
        getToOrBuilderList();
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    easemob.pb.Jid.JIDOrBuilder getToOrBuilder(
        int index);

    /**
     * <code>optional string reason = 5;</code>
     */
    boolean hasReason();
    /**
     * <code>optional string reason = 5;</code>
     */
    java.lang.String getReason();
    /**
     * <code>optional string reason = 5;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();

    /**
     * <code>optional string roster_ver = 6;</code>
     *
     * <pre>
     *server provide if there is change
     * </pre>
     */
    boolean hasRosterVer();
    /**
     * <code>optional string roster_ver = 6;</code>
     *
     * <pre>
     *server provide if there is change
     * </pre>
     */
    java.lang.String getRosterVer();
    /**
     * <code>optional string roster_ver = 6;</code>
     *
     * <pre>
     *server provide if there is change
     * </pre>
     */
    com.google.protobuf.ByteString
        getRosterVerBytes();

    /**
     * <code>optional bool bi_direction = 7;</code>
     *
     * <pre>
     *used to set both direction or oneway for blacklist
     * </pre>
     */
    boolean hasBiDirection();
    /**
     * <code>optional bool bi_direction = 7;</code>
     *
     * <pre>
     *used to set both direction or oneway for blacklist
     * </pre>
     */
    boolean getBiDirection();
  }
  /**
   * Protobuf type {@code easemob.pb.RosterBody}
   */
  public  static final class RosterBody extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:easemob.pb.RosterBody)
      RosterBodyOrBuilder {
    // Use RosterBody.newBuilder() to construct.
    private RosterBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RosterBody() {
      operation_ = 0;
      to_ = java.util.Collections.emptyList();
      reason_ = "";
      rosterVer_ = "";
      biDirection_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RosterBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              easemob.pb.Rosterbody.RosterBody.Operation value = easemob.pb.Rosterbody.RosterBody.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = rawValue;
              }
              break;
            }
            case 18: {
              easemob.pb.Rosterbody.RosterBody.Status.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(easemob.pb.Rosterbody.RosterBody.Status.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              easemob.pb.Jid.JID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = from_.toBuilder();
              }
              from_ = input.readMessage(easemob.pb.Jid.JID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(from_);
                from_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                to_ = new java.util.ArrayList<easemob.pb.Jid.JID>();
                mutable_bitField0_ |= 0x00000008;
              }
              to_.add(input.readMessage(easemob.pb.Jid.JID.parser(), extensionRegistry));
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              reason_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              rosterVer_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              biDirection_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          to_ = java.util.Collections.unmodifiableList(to_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              easemob.pb.Rosterbody.RosterBody.class, easemob.pb.Rosterbody.RosterBody.Builder.class);
    }

    /**
     * Protobuf enum {@code easemob.pb.RosterBody.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET_ROSTER = 0;</code>
       *
       * <pre>
       *get friend list 
       * </pre>
       */
      GET_ROSTER(0, 0),
      /**
       * <code>GET_BLACKLIST = 1;</code>
       *
       * <pre>
       *get blacklist
       * </pre>
       */
      GET_BLACKLIST(1, 1),
      /**
       * <code>ADD = 2;</code>
       *
       * <pre>
       *add friend
       * </pre>
       */
      ADD(2, 2),
      /**
       * <code>REMOVE = 3;</code>
       *
       * <pre>
       *remove friend
       * </pre>
       */
      REMOVE(3, 3),
      /**
       * <code>ACCEPT = 4;</code>
       *
       * <pre>
       *accept invitation
       * </pre>
       */
      ACCEPT(4, 4),
      /**
       * <code>DECLINE = 5;</code>
       *
       * <pre>
       *decline invitation
       * </pre>
       */
      DECLINE(5, 5),
      /**
       * <code>BAN = 6;</code>
       *
       * <pre>
       *add to blacklist
       * </pre>
       */
      BAN(6, 6),
      /**
       * <code>ALLOW = 7;</code>
       *
       * <pre>
       *release from blacklist
       * </pre>
       */
      ALLOW(7, 7),
      /**
       * <code>REMOTE_ACCEPT = 8;</code>
       *
       * <pre>
       * remote part accepted invitation
       * </pre>
       */
      REMOTE_ACCEPT(8, 8),
      /**
       * <code>REMOTE_DECLINE = 9;</code>
       *
       * <pre>
       * remote part declined invitation
       * </pre>
       */
      REMOTE_DECLINE(9, 9),
      ;

      /**
       * <code>GET_ROSTER = 0;</code>
       *
       * <pre>
       *get friend list 
       * </pre>
       */
      public static final int GET_ROSTER_VALUE = 0;
      /**
       * <code>GET_BLACKLIST = 1;</code>
       *
       * <pre>
       *get blacklist
       * </pre>
       */
      public static final int GET_BLACKLIST_VALUE = 1;
      /**
       * <code>ADD = 2;</code>
       *
       * <pre>
       *add friend
       * </pre>
       */
      public static final int ADD_VALUE = 2;
      /**
       * <code>REMOVE = 3;</code>
       *
       * <pre>
       *remove friend
       * </pre>
       */
      public static final int REMOVE_VALUE = 3;
      /**
       * <code>ACCEPT = 4;</code>
       *
       * <pre>
       *accept invitation
       * </pre>
       */
      public static final int ACCEPT_VALUE = 4;
      /**
       * <code>DECLINE = 5;</code>
       *
       * <pre>
       *decline invitation
       * </pre>
       */
      public static final int DECLINE_VALUE = 5;
      /**
       * <code>BAN = 6;</code>
       *
       * <pre>
       *add to blacklist
       * </pre>
       */
      public static final int BAN_VALUE = 6;
      /**
       * <code>ALLOW = 7;</code>
       *
       * <pre>
       *release from blacklist
       * </pre>
       */
      public static final int ALLOW_VALUE = 7;
      /**
       * <code>REMOTE_ACCEPT = 8;</code>
       *
       * <pre>
       * remote part accepted invitation
       * </pre>
       */
      public static final int REMOTE_ACCEPT_VALUE = 8;
      /**
       * <code>REMOTE_DECLINE = 9;</code>
       *
       * <pre>
       * remote part declined invitation
       * </pre>
       */
      public static final int REMOTE_DECLINE_VALUE = 9;


      public final int getNumber() {
        return value;
      }

      public static Operation valueOf(int value) {
        switch (value) {
          case 0: return GET_ROSTER;
          case 1: return GET_BLACKLIST;
          case 2: return ADD;
          case 3: return REMOVE;
          case 4: return ACCEPT;
          case 5: return DECLINE;
          case 6: return BAN;
          case 7: return ALLOW;
          case 8: return REMOTE_ACCEPT;
          case 9: return REMOTE_DECLINE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return easemob.pb.Rosterbody.RosterBody.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Operation(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.RosterBody.Operation)
    }

    public interface StatusOrBuilder extends
        // @@protoc_insertion_point(interface_extends:easemob.pb.RosterBody.Status)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
       */
      boolean hasErrorCode();
      /**
       * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
       */
      easemob.pb.Rosterbody.RosterBody.Status.ErrorCode getErrorCode();

      /**
       * <code>optional string description = 2;</code>
       */
      boolean hasDescription();
      /**
       * <code>optional string description = 2;</code>
       */
      java.lang.String getDescription();
      /**
       * <code>optional string description = 2;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();
    }
    /**
     * Protobuf type {@code easemob.pb.RosterBody.Status}
     */
    public  static final class Status extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:easemob.pb.RosterBody.Status)
        StatusOrBuilder {
      // Use Status.newBuilder() to construct.
      private Status(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private Status() {
        errorCode_ = 0;
        description_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Status(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                easemob.pb.Rosterbody.RosterBody.Status.ErrorCode value = easemob.pb.Rosterbody.RosterBody.Status.ErrorCode.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  errorCode_ = rawValue;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                description_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_Status_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                easemob.pb.Rosterbody.RosterBody.Status.class, easemob.pb.Rosterbody.RosterBody.Status.Builder.class);
      }

      /**
       * Protobuf enum {@code easemob.pb.RosterBody.Status.ErrorCode}
       */
      public enum ErrorCode
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>OK = 0;</code>
         */
        OK(0, 0),
        /**
         * <code>USER_NOT_EXIST = 1;</code>
         *
         * <pre>
         * user not exist
         * </pre>
         */
        USER_NOT_EXIST(1, 1),
        /**
         * <code>USER_ALREADY_FRIEND = 2;</code>
         *
         * <pre>
         * user already your friend
         * </pre>
         */
        USER_ALREADY_FRIEND(2, 2),
        /**
         * <code>USER_ALREADY_BLACKLIST = 3;</code>
         *
         * <pre>
         * user already in blacklist
         * </pre>
         */
        USER_ALREADY_BLACKLIST(3, 3),
        ;

        /**
         * <code>OK = 0;</code>
         */
        public static final int OK_VALUE = 0;
        /**
         * <code>USER_NOT_EXIST = 1;</code>
         *
         * <pre>
         * user not exist
         * </pre>
         */
        public static final int USER_NOT_EXIST_VALUE = 1;
        /**
         * <code>USER_ALREADY_FRIEND = 2;</code>
         *
         * <pre>
         * user already your friend
         * </pre>
         */
        public static final int USER_ALREADY_FRIEND_VALUE = 2;
        /**
         * <code>USER_ALREADY_BLACKLIST = 3;</code>
         *
         * <pre>
         * user already in blacklist
         * </pre>
         */
        public static final int USER_ALREADY_BLACKLIST_VALUE = 3;


        public final int getNumber() {
          return value;
        }

        public static ErrorCode valueOf(int value) {
          switch (value) {
            case 0: return OK;
            case 1: return USER_NOT_EXIST;
            case 2: return USER_ALREADY_FRIEND;
            case 3: return USER_ALREADY_BLACKLIST;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ErrorCode> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
                public ErrorCode findValueByNumber(int number) {
                  return ErrorCode.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return easemob.pb.Rosterbody.RosterBody.Status.getDescriptor().getEnumTypes().get(0);
        }

        private static final ErrorCode[] VALUES = values();

        public static ErrorCode valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private ErrorCode(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:easemob.pb.RosterBody.Status.ErrorCode)
      }

      private int bitField0_;
      public static final int ERROR_CODE_FIELD_NUMBER = 1;
      private int errorCode_;
      /**
       * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
       */
      public easemob.pb.Rosterbody.RosterBody.Status.ErrorCode getErrorCode() {
        easemob.pb.Rosterbody.RosterBody.Status.ErrorCode result = easemob.pb.Rosterbody.RosterBody.Status.ErrorCode.valueOf(errorCode_);
        return result == null ? easemob.pb.Rosterbody.RosterBody.Status.ErrorCode.OK : result;
      }

      public static final int DESCRIPTION_FIELD_NUMBER = 2;
      private volatile java.lang.Object description_;
      /**
       * <code>optional string description = 2;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, errorCode_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, errorCode_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static easemob.pb.Rosterbody.RosterBody.Status parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(easemob.pb.Rosterbody.RosterBody.Status prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code easemob.pb.RosterBody.Status}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:easemob.pb.RosterBody.Status)
          easemob.pb.Rosterbody.RosterBody.StatusOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_Status_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_Status_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  easemob.pb.Rosterbody.RosterBody.Status.class, easemob.pb.Rosterbody.RosterBody.Status.Builder.class);
        }

        // Construct using easemob.pb.Rosterbody.RosterBody.Status.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          errorCode_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          description_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_Status_descriptor;
        }

        public easemob.pb.Rosterbody.RosterBody.Status getDefaultInstanceForType() {
          return easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance();
        }

        public easemob.pb.Rosterbody.RosterBody.Status build() {
          easemob.pb.Rosterbody.RosterBody.Status result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public easemob.pb.Rosterbody.RosterBody.Status buildPartial() {
          easemob.pb.Rosterbody.RosterBody.Status result = new easemob.pb.Rosterbody.RosterBody.Status(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.errorCode_ = errorCode_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.description_ = description_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof easemob.pb.Rosterbody.RosterBody.Status) {
            return mergeFrom((easemob.pb.Rosterbody.RosterBody.Status)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(easemob.pb.Rosterbody.RosterBody.Status other) {
          if (other == easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance()) return this;
          if (other.hasErrorCode()) {
            setErrorCode(other.getErrorCode());
          }
          if (other.hasDescription()) {
            bitField0_ |= 0x00000002;
            description_ = other.description_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          easemob.pb.Rosterbody.RosterBody.Status parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (easemob.pb.Rosterbody.RosterBody.Status) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int errorCode_ = 0;
        /**
         * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
         */
        public boolean hasErrorCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
         */
        public easemob.pb.Rosterbody.RosterBody.Status.ErrorCode getErrorCode() {
          easemob.pb.Rosterbody.RosterBody.Status.ErrorCode result = easemob.pb.Rosterbody.RosterBody.Status.ErrorCode.valueOf(errorCode_);
          return result == null ? easemob.pb.Rosterbody.RosterBody.Status.ErrorCode.OK : result;
        }
        /**
         * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
         */
        public Builder setErrorCode(easemob.pb.Rosterbody.RosterBody.Status.ErrorCode value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          errorCode_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .easemob.pb.RosterBody.Status.ErrorCode error_code = 1;</code>
         */
        public Builder clearErrorCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          errorCode_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object description_ = "";
        /**
         * <code>optional string description = 2;</code>
         */
        public boolean hasDescription() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string description = 2;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              description_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string description = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string description = 2;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string description = 2;</code>
         */
        public Builder clearDescription() {
          bitField0_ = (bitField0_ & ~0x00000002);
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <code>optional string description = 2;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          description_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:easemob.pb.RosterBody.Status)
      }

      // @@protoc_insertion_point(class_scope:easemob.pb.RosterBody.Status)
      private static final easemob.pb.Rosterbody.RosterBody.Status DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new easemob.pb.Rosterbody.RosterBody.Status();
      }

      public static easemob.pb.Rosterbody.RosterBody.Status getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Status>
          PARSER = new com.google.protobuf.AbstractParser<Status>() {
        public Status parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new Status(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<Status> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Status> getParserForType() {
        return PARSER;
      }

      public easemob.pb.Rosterbody.RosterBody.Status getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
     */
    public easemob.pb.Rosterbody.RosterBody.Operation getOperation() {
      easemob.pb.Rosterbody.RosterBody.Operation result = easemob.pb.Rosterbody.RosterBody.Operation.valueOf(operation_);
      return result == null ? easemob.pb.Rosterbody.RosterBody.Operation.GET_ROSTER : result;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private easemob.pb.Rosterbody.RosterBody.Status status_;
    /**
     * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
     *
     * <pre>
     *server send to client this error with original operation id if some operation met error
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
     *
     * <pre>
     *server send to client this error with original operation id if some operation met error
     * </pre>
     */
    public easemob.pb.Rosterbody.RosterBody.Status getStatus() {
      return status_ == null ? easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
     *
     * <pre>
     *server send to client this error with original operation id if some operation met error
     * </pre>
     */
    public easemob.pb.Rosterbody.RosterBody.StatusOrBuilder getStatusOrBuilder() {
      return status_ == null ? easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance() : status_;
    }

    public static final int FROM_FIELD_NUMBER = 3;
    private easemob.pb.Jid.JID from_;
    /**
     * <code>optional .easemob.pb.JID from = 3;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .easemob.pb.JID from = 3;</code>
     */
    public easemob.pb.Jid.JID getFrom() {
      return from_ == null ? easemob.pb.Jid.JID.getDefaultInstance() : from_;
    }
    /**
     * <code>optional .easemob.pb.JID from = 3;</code>
     */
    public easemob.pb.Jid.JIDOrBuilder getFromOrBuilder() {
      return from_ == null ? easemob.pb.Jid.JID.getDefaultInstance() : from_;
    }

    public static final int TO_FIELD_NUMBER = 4;
    private java.util.List<easemob.pb.Jid.JID> to_;
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    public java.util.List<easemob.pb.Jid.JID> getToList() {
      return to_;
    }
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    public java.util.List<? extends easemob.pb.Jid.JIDOrBuilder> 
        getToOrBuilderList() {
      return to_;
    }
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    public int getToCount() {
      return to_.size();
    }
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    public easemob.pb.Jid.JID getTo(int index) {
      return to_.get(index);
    }
    /**
     * <code>repeated .easemob.pb.JID to = 4;</code>
     */
    public easemob.pb.Jid.JIDOrBuilder getToOrBuilder(
        int index) {
      return to_.get(index);
    }

    public static final int REASON_FIELD_NUMBER = 5;
    private volatile java.lang.Object reason_;
    /**
     * <code>optional string reason = 5;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string reason = 5;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reason = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROSTER_VER_FIELD_NUMBER = 6;
    private volatile java.lang.Object rosterVer_;
    /**
     * <code>optional string roster_ver = 6;</code>
     *
     * <pre>
     *server provide if there is change
     * </pre>
     */
    public boolean hasRosterVer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string roster_ver = 6;</code>
     *
     * <pre>
     *server provide if there is change
     * </pre>
     */
    public java.lang.String getRosterVer() {
      java.lang.Object ref = rosterVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rosterVer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string roster_ver = 6;</code>
     *
     * <pre>
     *server provide if there is change
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRosterVerBytes() {
      java.lang.Object ref = rosterVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rosterVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BI_DIRECTION_FIELD_NUMBER = 7;
    private boolean biDirection_;
    /**
     * <code>optional bool bi_direction = 7;</code>
     *
     * <pre>
     *used to set both direction or oneway for blacklist
     * </pre>
     */
    public boolean hasBiDirection() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool bi_direction = 7;</code>
     *
     * <pre>
     *used to set both direction or oneway for blacklist
     * </pre>
     */
    public boolean getBiDirection() {
      return biDirection_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getStatus());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getFrom());
      }
      for (int i = 0; i < to_.size(); i++) {
        output.writeMessage(4, to_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, reason_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, rosterVer_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(7, biDirection_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStatus());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFrom());
      }
      for (int i = 0; i < to_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, to_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, reason_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, rosterVer_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, biDirection_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static easemob.pb.Rosterbody.RosterBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static easemob.pb.Rosterbody.RosterBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static easemob.pb.Rosterbody.RosterBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static easemob.pb.Rosterbody.RosterBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(easemob.pb.Rosterbody.RosterBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code easemob.pb.RosterBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:easemob.pb.RosterBody)
        easemob.pb.Rosterbody.RosterBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                easemob.pb.Rosterbody.RosterBody.class, easemob.pb.Rosterbody.RosterBody.Builder.class);
      }

      // Construct using easemob.pb.Rosterbody.RosterBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
          getFromFieldBuilder();
          getToFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        operation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fromBuilder_ == null) {
          from_ = null;
        } else {
          fromBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (toBuilder_ == null) {
          to_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          toBuilder_.clear();
        }
        reason_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        rosterVer_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        biDirection_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return easemob.pb.Rosterbody.internal_static_easemob_pb_RosterBody_descriptor;
      }

      public easemob.pb.Rosterbody.RosterBody getDefaultInstanceForType() {
        return easemob.pb.Rosterbody.RosterBody.getDefaultInstance();
      }

      public easemob.pb.Rosterbody.RosterBody build() {
        easemob.pb.Rosterbody.RosterBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public easemob.pb.Rosterbody.RosterBody buildPartial() {
        easemob.pb.Rosterbody.RosterBody result = new easemob.pb.Rosterbody.RosterBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (fromBuilder_ == null) {
          result.from_ = from_;
        } else {
          result.from_ = fromBuilder_.build();
        }
        if (toBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            to_ = java.util.Collections.unmodifiableList(to_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.to_ = to_;
        } else {
          result.to_ = toBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.reason_ = reason_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.rosterVer_ = rosterVer_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.biDirection_ = biDirection_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof easemob.pb.Rosterbody.RosterBody) {
          return mergeFrom((easemob.pb.Rosterbody.RosterBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(easemob.pb.Rosterbody.RosterBody other) {
        if (other == easemob.pb.Rosterbody.RosterBody.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.hasFrom()) {
          mergeFrom(other.getFrom());
        }
        if (toBuilder_ == null) {
          if (!other.to_.isEmpty()) {
            if (to_.isEmpty()) {
              to_ = other.to_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureToIsMutable();
              to_.addAll(other.to_);
            }
            onChanged();
          }
        } else {
          if (!other.to_.isEmpty()) {
            if (toBuilder_.isEmpty()) {
              toBuilder_.dispose();
              toBuilder_ = null;
              to_ = other.to_;
              bitField0_ = (bitField0_ & ~0x00000008);
              toBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getToFieldBuilder() : null;
            } else {
              toBuilder_.addAllMessages(other.to_);
            }
          }
        }
        if (other.hasReason()) {
          bitField0_ |= 0x00000010;
          reason_ = other.reason_;
          onChanged();
        }
        if (other.hasRosterVer()) {
          bitField0_ |= 0x00000020;
          rosterVer_ = other.rosterVer_;
          onChanged();
        }
        if (other.hasBiDirection()) {
          setBiDirection(other.getBiDirection());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        easemob.pb.Rosterbody.RosterBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (easemob.pb.Rosterbody.RosterBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int operation_ = 0;
      /**
       * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
       */
      public easemob.pb.Rosterbody.RosterBody.Operation getOperation() {
        easemob.pb.Rosterbody.RosterBody.Operation result = easemob.pb.Rosterbody.RosterBody.Operation.valueOf(operation_);
        return result == null ? easemob.pb.Rosterbody.RosterBody.Operation.GET_ROSTER : result;
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
       */
      public Builder setOperation(easemob.pb.Rosterbody.RosterBody.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Operation operation = 1;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = 0;
        onChanged();
        return this;
      }

      private easemob.pb.Rosterbody.RosterBody.Status status_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          easemob.pb.Rosterbody.RosterBody.Status, easemob.pb.Rosterbody.RosterBody.Status.Builder, easemob.pb.Rosterbody.RosterBody.StatusOrBuilder> statusBuilder_;
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public easemob.pb.Rosterbody.RosterBody.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public Builder setStatus(easemob.pb.Rosterbody.RosterBody.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public Builder setStatus(
          easemob.pb.Rosterbody.RosterBody.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public Builder mergeStatus(easemob.pb.Rosterbody.RosterBody.Status value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              status_ != null &&
              status_ != easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance()) {
            status_ =
              easemob.pb.Rosterbody.RosterBody.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public easemob.pb.Rosterbody.RosterBody.Status.Builder getStatusBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      public easemob.pb.Rosterbody.RosterBody.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              easemob.pb.Rosterbody.RosterBody.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>optional .easemob.pb.RosterBody.Status status = 2;</code>
       *
       * <pre>
       *server send to client this error with original operation id if some operation met error
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          easemob.pb.Rosterbody.RosterBody.Status, easemob.pb.Rosterbody.RosterBody.Status.Builder, easemob.pb.Rosterbody.RosterBody.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              easemob.pb.Rosterbody.RosterBody.Status, easemob.pb.Rosterbody.RosterBody.Status.Builder, easemob.pb.Rosterbody.RosterBody.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      private easemob.pb.Jid.JID from_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          easemob.pb.Jid.JID, easemob.pb.Jid.JID.Builder, easemob.pb.Jid.JIDOrBuilder> fromBuilder_;
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public easemob.pb.Jid.JID getFrom() {
        if (fromBuilder_ == null) {
          return from_ == null ? easemob.pb.Jid.JID.getDefaultInstance() : from_;
        } else {
          return fromBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public Builder setFrom(easemob.pb.Jid.JID value) {
        if (fromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          from_ = value;
          onChanged();
        } else {
          fromBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public Builder setFrom(
          easemob.pb.Jid.JID.Builder builderForValue) {
        if (fromBuilder_ == null) {
          from_ = builderForValue.build();
          onChanged();
        } else {
          fromBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public Builder mergeFrom(easemob.pb.Jid.JID value) {
        if (fromBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              from_ != null &&
              from_ != easemob.pb.Jid.JID.getDefaultInstance()) {
            from_ =
              easemob.pb.Jid.JID.newBuilder(from_).mergeFrom(value).buildPartial();
          } else {
            from_ = value;
          }
          onChanged();
        } else {
          fromBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public Builder clearFrom() {
        if (fromBuilder_ == null) {
          from_ = null;
          onChanged();
        } else {
          fromBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public easemob.pb.Jid.JID.Builder getFromBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFromFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      public easemob.pb.Jid.JIDOrBuilder getFromOrBuilder() {
        if (fromBuilder_ != null) {
          return fromBuilder_.getMessageOrBuilder();
        } else {
          return from_ == null ?
              easemob.pb.Jid.JID.getDefaultInstance() : from_;
        }
      }
      /**
       * <code>optional .easemob.pb.JID from = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          easemob.pb.Jid.JID, easemob.pb.Jid.JID.Builder, easemob.pb.Jid.JIDOrBuilder> 
          getFromFieldBuilder() {
        if (fromBuilder_ == null) {
          fromBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              easemob.pb.Jid.JID, easemob.pb.Jid.JID.Builder, easemob.pb.Jid.JIDOrBuilder>(
                  getFrom(),
                  getParentForChildren(),
                  isClean());
          from_ = null;
        }
        return fromBuilder_;
      }

      private java.util.List<easemob.pb.Jid.JID> to_ =
        java.util.Collections.emptyList();
      private void ensureToIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          to_ = new java.util.ArrayList<easemob.pb.Jid.JID>(to_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          easemob.pb.Jid.JID, easemob.pb.Jid.JID.Builder, easemob.pb.Jid.JIDOrBuilder> toBuilder_;

      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public java.util.List<easemob.pb.Jid.JID> getToList() {
        if (toBuilder_ == null) {
          return java.util.Collections.unmodifiableList(to_);
        } else {
          return toBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public int getToCount() {
        if (toBuilder_ == null) {
          return to_.size();
        } else {
          return toBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public easemob.pb.Jid.JID getTo(int index) {
        if (toBuilder_ == null) {
          return to_.get(index);
        } else {
          return toBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder setTo(
          int index, easemob.pb.Jid.JID value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToIsMutable();
          to_.set(index, value);
          onChanged();
        } else {
          toBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder setTo(
          int index, easemob.pb.Jid.JID.Builder builderForValue) {
        if (toBuilder_ == null) {
          ensureToIsMutable();
          to_.set(index, builderForValue.build());
          onChanged();
        } else {
          toBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder addTo(easemob.pb.Jid.JID value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToIsMutable();
          to_.add(value);
          onChanged();
        } else {
          toBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder addTo(
          int index, easemob.pb.Jid.JID value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToIsMutable();
          to_.add(index, value);
          onChanged();
        } else {
          toBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder addTo(
          easemob.pb.Jid.JID.Builder builderForValue) {
        if (toBuilder_ == null) {
          ensureToIsMutable();
          to_.add(builderForValue.build());
          onChanged();
        } else {
          toBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder addTo(
          int index, easemob.pb.Jid.JID.Builder builderForValue) {
        if (toBuilder_ == null) {
          ensureToIsMutable();
          to_.add(index, builderForValue.build());
          onChanged();
        } else {
          toBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder addAllTo(
          java.lang.Iterable<? extends easemob.pb.Jid.JID> values) {
        if (toBuilder_ == null) {
          ensureToIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, to_);
          onChanged();
        } else {
          toBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder clearTo() {
        if (toBuilder_ == null) {
          to_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          toBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public Builder removeTo(int index) {
        if (toBuilder_ == null) {
          ensureToIsMutable();
          to_.remove(index);
          onChanged();
        } else {
          toBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public easemob.pb.Jid.JID.Builder getToBuilder(
          int index) {
        return getToFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public easemob.pb.Jid.JIDOrBuilder getToOrBuilder(
          int index) {
        if (toBuilder_ == null) {
          return to_.get(index);  } else {
          return toBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public java.util.List<? extends easemob.pb.Jid.JIDOrBuilder> 
           getToOrBuilderList() {
        if (toBuilder_ != null) {
          return toBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(to_);
        }
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public easemob.pb.Jid.JID.Builder addToBuilder() {
        return getToFieldBuilder().addBuilder(
            easemob.pb.Jid.JID.getDefaultInstance());
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public easemob.pb.Jid.JID.Builder addToBuilder(
          int index) {
        return getToFieldBuilder().addBuilder(
            index, easemob.pb.Jid.JID.getDefaultInstance());
      }
      /**
       * <code>repeated .easemob.pb.JID to = 4;</code>
       */
      public java.util.List<easemob.pb.Jid.JID.Builder> 
           getToBuilderList() {
        return getToFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          easemob.pb.Jid.JID, easemob.pb.Jid.JID.Builder, easemob.pb.Jid.JIDOrBuilder> 
          getToFieldBuilder() {
        if (toBuilder_ == null) {
          toBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              easemob.pb.Jid.JID, easemob.pb.Jid.JID.Builder, easemob.pb.Jid.JIDOrBuilder>(
                  to_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          to_ = null;
        }
        return toBuilder_;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>optional string reason = 5;</code>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string reason = 5;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reason_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reason = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reason = 5;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 5;</code>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000010);
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 5;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        reason_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rosterVer_ = "";
      /**
       * <code>optional string roster_ver = 6;</code>
       *
       * <pre>
       *server provide if there is change
       * </pre>
       */
      public boolean hasRosterVer() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string roster_ver = 6;</code>
       *
       * <pre>
       *server provide if there is change
       * </pre>
       */
      public java.lang.String getRosterVer() {
        java.lang.Object ref = rosterVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rosterVer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string roster_ver = 6;</code>
       *
       * <pre>
       *server provide if there is change
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRosterVerBytes() {
        java.lang.Object ref = rosterVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rosterVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string roster_ver = 6;</code>
       *
       * <pre>
       *server provide if there is change
       * </pre>
       */
      public Builder setRosterVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        rosterVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string roster_ver = 6;</code>
       *
       * <pre>
       *server provide if there is change
       * </pre>
       */
      public Builder clearRosterVer() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rosterVer_ = getDefaultInstance().getRosterVer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string roster_ver = 6;</code>
       *
       * <pre>
       *server provide if there is change
       * </pre>
       */
      public Builder setRosterVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        rosterVer_ = value;
        onChanged();
        return this;
      }

      private boolean biDirection_ ;
      /**
       * <code>optional bool bi_direction = 7;</code>
       *
       * <pre>
       *used to set both direction or oneway for blacklist
       * </pre>
       */
      public boolean hasBiDirection() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool bi_direction = 7;</code>
       *
       * <pre>
       *used to set both direction or oneway for blacklist
       * </pre>
       */
      public boolean getBiDirection() {
        return biDirection_;
      }
      /**
       * <code>optional bool bi_direction = 7;</code>
       *
       * <pre>
       *used to set both direction or oneway for blacklist
       * </pre>
       */
      public Builder setBiDirection(boolean value) {
        bitField0_ |= 0x00000040;
        biDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bi_direction = 7;</code>
       *
       * <pre>
       *used to set both direction or oneway for blacklist
       * </pre>
       */
      public Builder clearBiDirection() {
        bitField0_ = (bitField0_ & ~0x00000040);
        biDirection_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:easemob.pb.RosterBody)
    }

    // @@protoc_insertion_point(class_scope:easemob.pb.RosterBody)
    private static final easemob.pb.Rosterbody.RosterBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new easemob.pb.Rosterbody.RosterBody();
    }

    public static easemob.pb.Rosterbody.RosterBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RosterBody>
        PARSER = new com.google.protobuf.AbstractParser<RosterBody>() {
      public RosterBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RosterBody(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RosterBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RosterBody> getParserForType() {
      return PARSER;
    }

    public easemob.pb.Rosterbody.RosterBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_easemob_pb_RosterBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_easemob_pb_RosterBody_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_easemob_pb_RosterBody_Status_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_easemob_pb_RosterBody_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020rosterbody.proto\022\neasemob.pb\032\tjid.prot" +
      "o\"\273\004\n\nRosterBody\0223\n\toperation\030\001 \001(\0162 .ea" +
      "semob.pb.RosterBody.Operation\022-\n\006status\030" +
      "\002 \001(\0132\035.easemob.pb.RosterBody.Status\022\035\n\004" +
      "from\030\003 \001(\0132\017.easemob.pb.JID\022\033\n\002to\030\004 \003(\0132" +
      "\017.easemob.pb.JID\022\016\n\006reason\030\005 \001(\t\022\022\n\nrost" +
      "er_ver\030\006 \001(\t\022\024\n\014bi_direction\030\007 \001(\010\032\270\001\n\006S" +
      "tatus\022;\n\nerror_code\030\001 \001(\0162\'.easemob.pb.R" +
      "osterBody.Status.ErrorCode\022\023\n\013descriptio" +
      "n\030\002 \001(\t\"\\\n\tErrorCode\022\006\n\002OK\020\000\022\022\n\016USER_NOT",
      "_EXIST\020\001\022\027\n\023USER_ALREADY_FRIEND\020\002\022\032\n\026USE" +
      "R_ALREADY_BLACKLIST\020\003\"\227\001\n\tOperation\022\016\n\nG" +
      "ET_ROSTER\020\000\022\021\n\rGET_BLACKLIST\020\001\022\007\n\003ADD\020\002\022" +
      "\n\n\006REMOVE\020\003\022\n\n\006ACCEPT\020\004\022\013\n\007DECLINE\020\005\022\007\n\003" +
      "BAN\020\006\022\t\n\005ALLOW\020\007\022\021\n\rREMOTE_ACCEPT\020\010\022\022\n\016R" +
      "EMOTE_DECLINE\020\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          easemob.pb.Jid.getDescriptor(),
        }, assigner);
    internal_static_easemob_pb_RosterBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_easemob_pb_RosterBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_easemob_pb_RosterBody_descriptor,
        new java.lang.String[] { "Operation", "Status", "From", "To", "Reason", "RosterVer", "BiDirection", });
    internal_static_easemob_pb_RosterBody_Status_descriptor =
      internal_static_easemob_pb_RosterBody_descriptor.getNestedTypes().get(0);
    internal_static_easemob_pb_RosterBody_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_easemob_pb_RosterBody_Status_descriptor,
        new java.lang.String[] { "ErrorCode", "Description", });
    easemob.pb.Jid.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
