// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statisticsbody.proto

package easemob.pb;

public final class Statisticsbody {
  private Statisticsbody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StatisticsBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:easemob.pb.StatisticsBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
     */
    boolean hasOperation();
    /**
     * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
     */
    easemob.pb.Statisticsbody.StatisticsBody.Operation getOperation();

    /**
     * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
     */
    boolean hasOs();
    /**
     * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
     */
    easemob.pb.Statisticsbody.StatisticsBody.OsType getOs();

    /**
     * <code>optional string version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 3;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
     */
    boolean hasNetwork();
    /**
     * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
     */
    easemob.pb.Statisticsbody.StatisticsBody.NetworkType getNetwork();

    /**
     * <code>optional uint32 im_time = 5;</code>
     */
    boolean hasImTime();
    /**
     * <code>optional uint32 im_time = 5;</code>
     */
    int getImTime();

    /**
     * <code>optional uint32 chat_time = 6;</code>
     */
    boolean hasChatTime();
    /**
     * <code>optional uint32 chat_time = 6;</code>
     */
    int getChatTime();
  }
  /**
   * Protobuf type {@code easemob.pb.StatisticsBody}
   */
  public  static final class StatisticsBody extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:easemob.pb.StatisticsBody)
      StatisticsBodyOrBuilder {
    // Use StatisticsBody.newBuilder() to construct.
    private StatisticsBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StatisticsBody() {
      operation_ = 0;
      os_ = 0;
      version_ = "";
      network_ = 0;
      imTime_ = 0;
      chatTime_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StatisticsBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              easemob.pb.Statisticsbody.StatisticsBody.Operation value = easemob.pb.Statisticsbody.StatisticsBody.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              easemob.pb.Statisticsbody.StatisticsBody.OsType value = easemob.pb.Statisticsbody.StatisticsBody.OsType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                os_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              version_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              easemob.pb.Statisticsbody.StatisticsBody.NetworkType value = easemob.pb.Statisticsbody.StatisticsBody.NetworkType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                network_ = rawValue;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              imTime_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              chatTime_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return easemob.pb.Statisticsbody.internal_static_easemob_pb_StatisticsBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return easemob.pb.Statisticsbody.internal_static_easemob_pb_StatisticsBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              easemob.pb.Statisticsbody.StatisticsBody.class, easemob.pb.Statisticsbody.StatisticsBody.Builder.class);
    }

    /**
     * Protobuf enum {@code easemob.pb.StatisticsBody.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INFORMATION = 0;</code>
       *
       * <pre>
       * sdk send information when login, such as os type, sdk version, login time, etc
       * </pre>
       */
      INFORMATION(0, 0),
      /**
       * <code>USER_REMOVED = 1;</code>
       *
       * <pre>
       * user was removed from server side while user is online
       * </pre>
       */
      USER_REMOVED(1, 1),
      /**
       * <code>USER_LOGIN_ANOTHER_DEVICE = 2;</code>
       *
       * <pre>
       * user login on another device
       * </pre>
       */
      USER_LOGIN_ANOTHER_DEVICE(2, 2),
      ;

      /**
       * <code>INFORMATION = 0;</code>
       *
       * <pre>
       * sdk send information when login, such as os type, sdk version, login time, etc
       * </pre>
       */
      public static final int INFORMATION_VALUE = 0;
      /**
       * <code>USER_REMOVED = 1;</code>
       *
       * <pre>
       * user was removed from server side while user is online
       * </pre>
       */
      public static final int USER_REMOVED_VALUE = 1;
      /**
       * <code>USER_LOGIN_ANOTHER_DEVICE = 2;</code>
       *
       * <pre>
       * user login on another device
       * </pre>
       */
      public static final int USER_LOGIN_ANOTHER_DEVICE_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      public static Operation valueOf(int value) {
        switch (value) {
          case 0: return INFORMATION;
          case 1: return USER_REMOVED;
          case 2: return USER_LOGIN_ANOTHER_DEVICE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return easemob.pb.Statisticsbody.StatisticsBody.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Operation(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.StatisticsBody.Operation)
    }

    /**
     * Protobuf enum {@code easemob.pb.StatisticsBody.OsType}
     */
    public enum OsType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OS_IOS = 0;</code>
       */
      OS_IOS(0, 0),
      /**
       * <code>OS_ANDROID = 1;</code>
       */
      OS_ANDROID(1, 1),
      /**
       * <code>OS_LINUX = 2;</code>
       */
      OS_LINUX(2, 2),
      /**
       * <code>OS_OSX = 3;</code>
       */
      OS_OSX(3, 3),
      /**
       * <code>OS_WIN = 4;</code>
       */
      OS_WIN(4, 4),
      /**
       * <code>OS_OTHER = 16;</code>
       */
      OS_OTHER(5, 16),
      ;

      /**
       * <code>OS_IOS = 0;</code>
       */
      public static final int OS_IOS_VALUE = 0;
      /**
       * <code>OS_ANDROID = 1;</code>
       */
      public static final int OS_ANDROID_VALUE = 1;
      /**
       * <code>OS_LINUX = 2;</code>
       */
      public static final int OS_LINUX_VALUE = 2;
      /**
       * <code>OS_OSX = 3;</code>
       */
      public static final int OS_OSX_VALUE = 3;
      /**
       * <code>OS_WIN = 4;</code>
       */
      public static final int OS_WIN_VALUE = 4;
      /**
       * <code>OS_OTHER = 16;</code>
       */
      public static final int OS_OTHER_VALUE = 16;


      public final int getNumber() {
        return value;
      }

      public static OsType valueOf(int value) {
        switch (value) {
          case 0: return OS_IOS;
          case 1: return OS_ANDROID;
          case 2: return OS_LINUX;
          case 3: return OS_OSX;
          case 4: return OS_WIN;
          case 16: return OS_OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OsType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OsType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OsType>() {
              public OsType findValueByNumber(int number) {
                return OsType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return easemob.pb.Statisticsbody.StatisticsBody.getDescriptor().getEnumTypes().get(1);
      }

      private static final OsType[] VALUES = values();

      public static OsType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private OsType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.StatisticsBody.OsType)
    }

    /**
     * Protobuf enum {@code easemob.pb.StatisticsBody.NetworkType}
     */
    public enum NetworkType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NETWORK_NONE = 0;</code>
       */
      NETWORK_NONE(0, 0),
      /**
       * <code>NETWORK_WIFI = 1;</code>
       */
      NETWORK_WIFI(1, 1),
      /**
       * <code>NETWORK_4G = 2;</code>
       */
      NETWORK_4G(2, 2),
      /**
       * <code>NETWORK_3G = 3;</code>
       */
      NETWORK_3G(3, 3),
      /**
       * <code>NETWORK_2G = 4;</code>
       */
      NETWORK_2G(4, 4),
      /**
       * <code>NETWORK_WIRE = 5;</code>
       */
      NETWORK_WIRE(5, 5),
      ;

      /**
       * <code>NETWORK_NONE = 0;</code>
       */
      public static final int NETWORK_NONE_VALUE = 0;
      /**
       * <code>NETWORK_WIFI = 1;</code>
       */
      public static final int NETWORK_WIFI_VALUE = 1;
      /**
       * <code>NETWORK_4G = 2;</code>
       */
      public static final int NETWORK_4G_VALUE = 2;
      /**
       * <code>NETWORK_3G = 3;</code>
       */
      public static final int NETWORK_3G_VALUE = 3;
      /**
       * <code>NETWORK_2G = 4;</code>
       */
      public static final int NETWORK_2G_VALUE = 4;
      /**
       * <code>NETWORK_WIRE = 5;</code>
       */
      public static final int NETWORK_WIRE_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      public static NetworkType valueOf(int value) {
        switch (value) {
          case 0: return NETWORK_NONE;
          case 1: return NETWORK_WIFI;
          case 2: return NETWORK_4G;
          case 3: return NETWORK_3G;
          case 4: return NETWORK_2G;
          case 5: return NETWORK_WIRE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetworkType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NetworkType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetworkType>() {
              public NetworkType findValueByNumber(int number) {
                return NetworkType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return easemob.pb.Statisticsbody.StatisticsBody.getDescriptor().getEnumTypes().get(2);
      }

      private static final NetworkType[] VALUES = values();

      public static NetworkType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private NetworkType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:easemob.pb.StatisticsBody.NetworkType)
    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
     */
    public easemob.pb.Statisticsbody.StatisticsBody.Operation getOperation() {
      easemob.pb.Statisticsbody.StatisticsBody.Operation result = easemob.pb.Statisticsbody.StatisticsBody.Operation.valueOf(operation_);
      return result == null ? easemob.pb.Statisticsbody.StatisticsBody.Operation.INFORMATION : result;
    }

    public static final int OS_FIELD_NUMBER = 2;
    private int os_;
    /**
     * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
     */
    public boolean hasOs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
     */
    public easemob.pb.Statisticsbody.StatisticsBody.OsType getOs() {
      easemob.pb.Statisticsbody.StatisticsBody.OsType result = easemob.pb.Statisticsbody.StatisticsBody.OsType.valueOf(os_);
      return result == null ? easemob.pb.Statisticsbody.StatisticsBody.OsType.OS_IOS : result;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object version_;
    /**
     * <code>optional string version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string version = 3;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETWORK_FIELD_NUMBER = 4;
    private int network_;
    /**
     * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
     */
    public boolean hasNetwork() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
     */
    public easemob.pb.Statisticsbody.StatisticsBody.NetworkType getNetwork() {
      easemob.pb.Statisticsbody.StatisticsBody.NetworkType result = easemob.pb.Statisticsbody.StatisticsBody.NetworkType.valueOf(network_);
      return result == null ? easemob.pb.Statisticsbody.StatisticsBody.NetworkType.NETWORK_NONE : result;
    }

    public static final int IM_TIME_FIELD_NUMBER = 5;
    private int imTime_;
    /**
     * <code>optional uint32 im_time = 5;</code>
     */
    public boolean hasImTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 im_time = 5;</code>
     */
    public int getImTime() {
      return imTime_;
    }

    public static final int CHAT_TIME_FIELD_NUMBER = 6;
    private int chatTime_;
    /**
     * <code>optional uint32 chat_time = 6;</code>
     */
    public boolean hasChatTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 chat_time = 6;</code>
     */
    public int getChatTime() {
      return chatTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, os_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, network_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, imTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, chatTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, os_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, network_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, imTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, chatTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static easemob.pb.Statisticsbody.StatisticsBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(easemob.pb.Statisticsbody.StatisticsBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code easemob.pb.StatisticsBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:easemob.pb.StatisticsBody)
        easemob.pb.Statisticsbody.StatisticsBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return easemob.pb.Statisticsbody.internal_static_easemob_pb_StatisticsBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return easemob.pb.Statisticsbody.internal_static_easemob_pb_StatisticsBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                easemob.pb.Statisticsbody.StatisticsBody.class, easemob.pb.Statisticsbody.StatisticsBody.Builder.class);
      }

      // Construct using easemob.pb.Statisticsbody.StatisticsBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        operation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        os_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        network_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        imTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        chatTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return easemob.pb.Statisticsbody.internal_static_easemob_pb_StatisticsBody_descriptor;
      }

      public easemob.pb.Statisticsbody.StatisticsBody getDefaultInstanceForType() {
        return easemob.pb.Statisticsbody.StatisticsBody.getDefaultInstance();
      }

      public easemob.pb.Statisticsbody.StatisticsBody build() {
        easemob.pb.Statisticsbody.StatisticsBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public easemob.pb.Statisticsbody.StatisticsBody buildPartial() {
        easemob.pb.Statisticsbody.StatisticsBody result = new easemob.pb.Statisticsbody.StatisticsBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.network_ = network_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.imTime_ = imTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.chatTime_ = chatTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof easemob.pb.Statisticsbody.StatisticsBody) {
          return mergeFrom((easemob.pb.Statisticsbody.StatisticsBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(easemob.pb.Statisticsbody.StatisticsBody other) {
        if (other == easemob.pb.Statisticsbody.StatisticsBody.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasOs()) {
          setOs(other.getOs());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000004;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasNetwork()) {
          setNetwork(other.getNetwork());
        }
        if (other.hasImTime()) {
          setImTime(other.getImTime());
        }
        if (other.hasChatTime()) {
          setChatTime(other.getChatTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        easemob.pb.Statisticsbody.StatisticsBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (easemob.pb.Statisticsbody.StatisticsBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int operation_ = 0;
      /**
       * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
       */
      public easemob.pb.Statisticsbody.StatisticsBody.Operation getOperation() {
        easemob.pb.Statisticsbody.StatisticsBody.Operation result = easemob.pb.Statisticsbody.StatisticsBody.Operation.valueOf(operation_);
        return result == null ? easemob.pb.Statisticsbody.StatisticsBody.Operation.INFORMATION : result;
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
       */
      public Builder setOperation(easemob.pb.Statisticsbody.StatisticsBody.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.Operation operation = 1;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = 0;
        onChanged();
        return this;
      }

      private int os_ = 0;
      /**
       * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
       */
      public boolean hasOs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
       */
      public easemob.pb.Statisticsbody.StatisticsBody.OsType getOs() {
        easemob.pb.Statisticsbody.StatisticsBody.OsType result = easemob.pb.Statisticsbody.StatisticsBody.OsType.valueOf(os_);
        return result == null ? easemob.pb.Statisticsbody.StatisticsBody.OsType.OS_IOS : result;
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
       */
      public Builder setOs(easemob.pb.Statisticsbody.StatisticsBody.OsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        os_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.OsType os = 2;</code>
       */
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        os_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string version = 3;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 3;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      private int network_ = 0;
      /**
       * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
       */
      public boolean hasNetwork() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
       */
      public easemob.pb.Statisticsbody.StatisticsBody.NetworkType getNetwork() {
        easemob.pb.Statisticsbody.StatisticsBody.NetworkType result = easemob.pb.Statisticsbody.StatisticsBody.NetworkType.valueOf(network_);
        return result == null ? easemob.pb.Statisticsbody.StatisticsBody.NetworkType.NETWORK_NONE : result;
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
       */
      public Builder setNetwork(easemob.pb.Statisticsbody.StatisticsBody.NetworkType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        network_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .easemob.pb.StatisticsBody.NetworkType network = 4;</code>
       */
      public Builder clearNetwork() {
        bitField0_ = (bitField0_ & ~0x00000008);
        network_ = 0;
        onChanged();
        return this;
      }

      private int imTime_ ;
      /**
       * <code>optional uint32 im_time = 5;</code>
       */
      public boolean hasImTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 im_time = 5;</code>
       */
      public int getImTime() {
        return imTime_;
      }
      /**
       * <code>optional uint32 im_time = 5;</code>
       */
      public Builder setImTime(int value) {
        bitField0_ |= 0x00000010;
        imTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 im_time = 5;</code>
       */
      public Builder clearImTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imTime_ = 0;
        onChanged();
        return this;
      }

      private int chatTime_ ;
      /**
       * <code>optional uint32 chat_time = 6;</code>
       */
      public boolean hasChatTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 chat_time = 6;</code>
       */
      public int getChatTime() {
        return chatTime_;
      }
      /**
       * <code>optional uint32 chat_time = 6;</code>
       */
      public Builder setChatTime(int value) {
        bitField0_ |= 0x00000020;
        chatTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 chat_time = 6;</code>
       */
      public Builder clearChatTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        chatTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:easemob.pb.StatisticsBody)
    }

    // @@protoc_insertion_point(class_scope:easemob.pb.StatisticsBody)
    private static final easemob.pb.Statisticsbody.StatisticsBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new easemob.pb.Statisticsbody.StatisticsBody();
    }

    public static easemob.pb.Statisticsbody.StatisticsBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StatisticsBody>
        PARSER = new com.google.protobuf.AbstractParser<StatisticsBody>() {
      public StatisticsBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new StatisticsBody(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<StatisticsBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatisticsBody> getParserForType() {
      return PARSER;
    }

    public easemob.pb.Statisticsbody.StatisticsBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_easemob_pb_StatisticsBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_easemob_pb_StatisticsBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024statisticsbody.proto\022\neasemob.pb\"\204\004\n\016S" +
      "tatisticsBody\0227\n\toperation\030\001 \001(\0162$.easem" +
      "ob.pb.StatisticsBody.Operation\022-\n\002os\030\002 \001" +
      "(\0162!.easemob.pb.StatisticsBody.OsType\022\017\n" +
      "\007version\030\003 \001(\t\0227\n\007network\030\004 \001(\0162&.easemo" +
      "b.pb.StatisticsBody.NetworkType\022\017\n\007im_ti" +
      "me\030\005 \001(\r\022\021\n\tchat_time\030\006 \001(\r\"M\n\tOperation" +
      "\022\017\n\013INFORMATION\020\000\022\020\n\014USER_REMOVED\020\001\022\035\n\031U" +
      "SER_LOGIN_ANOTHER_DEVICE\020\002\"X\n\006OsType\022\n\n\006" +
      "OS_IOS\020\000\022\016\n\nOS_ANDROID\020\001\022\014\n\010OS_LINUX\020\002\022\n",
      "\n\006OS_OSX\020\003\022\n\n\006OS_WIN\020\004\022\014\n\010OS_OTHER\020\020\"s\n\013" +
      "NetworkType\022\020\n\014NETWORK_NONE\020\000\022\020\n\014NETWORK" +
      "_WIFI\020\001\022\016\n\nNETWORK_4G\020\002\022\016\n\nNETWORK_3G\020\003\022" +
      "\016\n\nNETWORK_2G\020\004\022\020\n\014NETWORK_WIRE\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_easemob_pb_StatisticsBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_easemob_pb_StatisticsBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_easemob_pb_StatisticsBody_descriptor,
        new java.lang.String[] { "Operation", "Os", "Version", "Network", "ImTime", "ChatTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
